In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O

In [2]:
!pip uninstall -y transformers accelerate -q
!pip install -q transformers==4.43.0 accelerate==0.30.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 72.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 kB 20.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 38.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 96.8 MB/s eta 0:00:00

### Import flickr-30k dataset

In [3]:
import os

BASE = "/kaggle/input/datasets/hsankesara/flickr-image-dataset/flickr30k_images"
IMG_DIR = os.path.join(BASE, "flickr30k_images")
CAPTION_FILE = "/kaggle/input/datasets/hsankesara/flickr-image-dataset/flickr30k_images/results.csv"

print("Image folder:", IMG_DIR)
print("Caption file:", CAPTION_FILE)

Image folder: /kaggle/input/datasets/hsankesara/flickr-image-dataset/flickr30k_images/flickr30k_images
Caption file: /kaggle/input/datasets/hsankesara/flickr-image-dataset/flickr30k_images/results.csv

In [4]:
print("Number of images:", len(os.listdir(IMG_DIR)))
print(os.listdir(IMG_DIR)[:10])

Number of images: 31785
['2715746315.jpg', '3463034205.jpg', '268704620.jpg', '2673564214.jpg', '7535037918.jpg', '4912369161.jpg', '4828071602.jpg', '6802728196.jpg', '3346289227.jpg', '3217056901.jpg']

In [5]:

df = pd.read_csv(CAPTION_FILE, sep='|')
df.head()

,image_name,comment_number,comment
0,1000092795.jpg,0,Two young guys with shaggy hair look at their...
1,1000092795.jpg,1,"Two young , White males are outside near many..."
2,1000092795.jpg,2,Two men in green shirts are standing in a yard .
3,1000092795.jpg,3,A man in a blue shirt standing in a garden .
4,1000092795.jpg,4,Two friends enjoy time spent together .

In [6]:
df.columns = df.columns.str.strip()

In [7]:
!pip -q install open_clip_torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 23.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 2.8 MB/s eta 0:00:00

In [8]:
import torch
import open_clip
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

clip_model_b32, _, preprocess_b32 = open_clip.create_model_and_transforms(
    "ViT-B-32",
    pretrained="laion2b_s34b_b79k"
)
tokenizer_b32 = open_clip.get_tokenizer("ViT-B-32")

clip_model_b32 = clip_model_b32.to(device).eval()
print("Device:", device)

open_clip_model.safetensors:   0%|          | 0.00/605M [00:00<?, ?B/s]

Device: cuda

In [9]:
import torch
import open_clip

device = "cuda" if torch.cuda.is_available() else "cpu"

clip_model_b16, _, preprocess_b16 = open_clip.create_model_and_transforms(
    "ViT-B-16",
    pretrained="laion2b_s34b_b88k"
)

tokenizer_b16 = open_clip.get_tokenizer("ViT-B-16")

clip_model_b16 = clip_model_b16.to(device).eval()

print("Loaded ViT-B/16 on:", device)

open_clip_model.safetensors:   0%|          | 0.00/599M [00:00<?, ?B/s]

Loaded ViT-B/16 on: cuda

In [10]:
CAPTION_N = 200000

cap_df = df.sample(n=min(CAPTION_N, len(df)), random_state=42).reset_index(drop=True)
captions = cap_df["comment"].astype(str).tolist()

print("Captions in pool:", len(captions))

Captions in pool: 158915

In [11]:
@torch.no_grad()
def encode_texts_b16(text_list, batch_size=256):
    embs = []
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        tokens = tokenizer_b16(batch).to(device)
        feat = clip_model_b16.encode_text(tokens)
        feat = feat / feat.norm(dim=-1, keepdim=True)
        embs.append(feat.cpu())
    return torch.cat(embs, dim=0)

In [12]:
from PIL import Image
import matplotlib.pyplot as plt
import os, random

@torch.no_grad()
def encode_image_b16(img_path):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess_b16(img).unsqueeze(0).to(device)
    feat = clip_model_b16.encode_image(img_in)
    feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.cpu(), img

In [13]:
@torch.no_grad()
def encode_texts_b32(text_list, batch_size=256):
    embs = []
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        tokens = tokenizer_b32(batch).to(device)
        feat = clip_model_b32.encode_text(tokens)
        feat = feat / feat.norm(dim=-1, keepdim=True)
        embs.append(feat.cpu())
    return torch.cat(embs, dim=0)

In [14]:
from PIL import Image
import matplotlib.pyplot as plt
import os, random

@torch.no_grad()
def encode_image_b32(img_path):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess_b32(img).unsqueeze(0).to(device)
    feat = clip_model_b32.encode_image(img_in)
    feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.cpu(), img

In [15]:
import transformers, accelerate, torch
print(transformers.__version__)
print(accelerate.__version__)
print(torch.__version__)

4.43.0
0.30.0
2.9.0+cu126

### Setting up the LLM(Phi-3.5-vision-instruct)

In [16]:
import os
import torch
from transformers import AutoConfig, AutoProcessor, AutoModelForCausalLM
from huggingface_hub import login

os.environ["HF_HOME"] = "/kaggle/working/hf_cache"
os.environ["TRANSFORMERS_CACHE"] = "/kaggle/working/hf_cache"

# Login
login(token="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")

VLM_NAME = "microsoft/Phi-3.5-vision-instruct"

config = AutoConfig.from_pretrained(
    VLM_NAME,
    trust_remote_code=True
)
config._attn_implementation = "eager"

processor = AutoProcessor.from_pretrained(
    VLM_NAME,
    trust_remote_code=True  
)

phi_model = AutoModelForCausalLM.from_pretrained(
    VLM_NAME,
    config=config,
    trust_remote_code=True,
    device_map="auto",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
).eval()

2026-03-30 12:03:52.068305: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774872232.294064      24 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774872232.354666      24 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1774872232.884564      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774872232.884596      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774872232.884603      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774872232.884608      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

config.json: 0.00B [00:00, ?B/s]

configuration_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- configuration_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

processor_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

processing_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- processing_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
/usr/local/lib/python3.12/dist-packages/transformers/models/auto/image_processing_auto.py:513: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(

preprocessor_config.json:   0%|          | 0.00/442 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/670 [00:00<?, ?B/s]

modeling_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- modeling_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.35G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/136 [00:00<?, ?B/s]

## Analysis of responses: (ViT-B/16 vs ViT-B/32)

In [17]:
CAPTION_N = 20000

cap_df = df.sample(n=min(CAPTION_N, len(df)), random_state=42).reset_index(drop=True)

captions = cap_df["comment"].astype(str).tolist()

print("Captions in pool:", len(captions))

Captions in pool: 20000

In [18]:
@torch.no_grad()
def encode_captions_b16(text_list, batch_size=256):
    embs = []

    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]

        tokens = open_clip.tokenize(batch).to(device)

        feat = clip_model_b16.encode_text(tokens)

        # Normalize (important for cosine similarity)
        feat = feat / feat.norm(dim=-1, keepdim=True)

        embs.append(feat.cpu())

        if i % (batch_size * 10) == 0:
            print(f"Processed {i}/{len(text_list)} captions")

    return torch.cat(embs, dim=0)

In [19]:
@torch.no_grad()
def encode_captions_b32(text_list, batch_size=256):
    embs = []

    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]

        tokens = open_clip.tokenize(batch).to(device)

        feat = clip_model_b32.encode_text(tokens)

        # Normalize (important for cosine similarity)
        feat = feat / feat.norm(dim=-1, keepdim=True)

        embs.append(feat.cpu())

        if i % (batch_size * 10) == 0:
            print(f"Processed {i}/{len(text_list)} captions")

    return torch.cat(embs, dim=0)

In [20]:
caption_embs_b16 = encode_captions_b16(captions, batch_size=256)

print("Caption embeddings:", caption_embs_b16.shape)

Processed 0/20000 captions
Processed 2560/20000 captions
Processed 5120/20000 captions
Processed 7680/20000 captions
Processed 10240/20000 captions
Processed 12800/20000 captions
Processed 15360/20000 captions
Processed 17920/20000 captions
Caption embeddings: torch.Size([20000, 512])

In [21]:
caption_embs_b32 = encode_captions_b32(captions, batch_size=256)
print("Caption embeddings:", caption_embs_b32.shape)

Processed 0/20000 captions
Processed 2560/20000 captions
Processed 5120/20000 captions
Processed 7680/20000 captions
Processed 10240/20000 captions
Processed 12800/20000 captions
Processed 15360/20000 captions
Processed 17920/20000 captions
Caption embeddings: torch.Size([20000, 512])

In [22]:
import os
import random
import re
import torch
import pandas as pd
from PIL import Image


def clean_answer(text):
    text = text.strip()

    stop_markers = [
        "# User", "# Assistant", "# Input", "# Output", "##",
        "<|user|>", "<|assistant|>", "<|end|>"
    ]

    for marker in stop_markers:
        if marker in text:
            text = text.split(marker)[0].strip()

    sentences = re.split(r'(?<=[.!?])\s+', text)
    return " ".join(sentences[:1]).strip()


@torch.no_grad()
def encode_image_b16(img_path):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess_b16(img).unsqueeze(0).to(device)
    feat = clip_model_b16.encode_image(img_in)
    feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.cpu(), img


def get_random_image_embeddings_b16(img_dir, num_samples=10, seed=42):
    random.seed(seed)

    all_images = [
        os.path.join(img_dir, f)
        for f in os.listdir(img_dir)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    if not all_images:
        raise ValueError(f"No image files found in: {img_dir}")

    sampled_images = random.sample(all_images, min(num_samples, len(all_images)))

    embeddings = []
    image_objects = []
    image_paths = []

    for img_path in sampled_images:
        feat, img = encode_image_b16(img_path)
        embeddings.append(feat)
        image_objects.append(img)
        image_paths.append(img_path)

    embeddings = torch.cat(embeddings, dim=0)   # (N, D)
    return embeddings, image_objects, image_paths

In [23]:
@torch.no_grad()
def encode_image_b32(img_path):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess_b32(img).unsqueeze(0).to(device)
    feat = clip_model_b32.encode_image(img_in)
    feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.cpu(), img


def get_random_image_embeddings_b32(img_dir, num_samples=10, seed=42):
    random.seed(seed)

    all_images = [
        os.path.join(img_dir, f)
        for f in os.listdir(img_dir)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    if not all_images:
        raise ValueError(f"No image files found in: {img_dir}")

    sampled_images = random.sample(all_images, min(num_samples, len(all_images)))

    embeddings = []
    image_objects = []
    image_paths = []

    for img_path in sampled_images:
        feat, img = encode_image_b32(img_path)
        embeddings.append(feat)
        image_objects.append(img)
        image_paths.append(img_path)

    embeddings = torch.cat(embeddings, dim=0)   # (N, D)
    return embeddings, image_objects, image_paths

In [ ]:
def retrieve_topk_captions_for_image(image_emb, caption_embs, captions, caption_image_names, k=10):

    if image_emb.dim() == 1:
        image_emb = image_emb.unsqueeze(0)

    sims = image_emb @ caption_embs.T
    top_scores, top_idx = torch.topk(sims, k=min(k, len(captions)), dim=1)

    results = []
    for score, idx in zip(top_scores[0].tolist(), top_idx[0].tolist()):
        results.append({
            "score": score,
            "caption": captions[idx],
            "caption_image_name": caption_image_names[idx]
        })

    return results

In [25]:
@torch.no_grad()
def generate_with_rag_phi(img_path, retrieved_caps, phi_model, processor, max_new_tokens=25):
    image = Image.open(img_path).convert("RGB")

    context_block = "\n".join([f"- {cap}" for _, cap in retrieved_caps])

    prompt = f"""<|user|>
<|image_1|>
Describe this image in one sentence.

Helpful retrieved captions:
{context_block}

Only answer with the description sentence.
<|end|>
<|assistant|>
"""
    inputs = processor(
            text=prompt,
            images=image,
            return_tensors="pt"
        )

    for k, v in inputs.items():
        if hasattr(v, "to"):
            inputs[k] = v.to(phi_model.device)

    outputs = phi_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        use_cache=True,   # can keep True for speed
        eos_token_id=processor.tokenizer.eos_token_id,
        pad_token_id=processor.tokenizer.eos_token_id
    )

    generated_ids = outputs[:, inputs["input_ids"].shape[1]:]

    raw_answer = processor.tokenizer.decode(
        generated_ids[0],
        skip_special_tokens=True
    ).strip()

    return raw_answer, clean_answer(raw_answer)

### Comparing responses obtained for each of the 2 encoders

In [26]:
import os
import pandas as pd

def run_encoder16_vs_encoder32_rag_pipeline(
    img_dir,
    caption_embs_b16,
    caption_embs_b32,
    captions,
    caption_image_names,
    phi_model,
    phi_processor,
    num_samples=100,
    seed=42,
    k=5,
    save_every=25,
    save_path="/kaggle/working/encoder16_vs_encoder32_rag.csv"
):
    _, _, sampled_img_paths = get_random_image_embeddings_b16(
        img_dir,
        num_samples=num_samples,
        seed=seed
    )

    outputs = []

    for i, img_path in enumerate(sampled_img_paths):
        image_name = os.path.basename(img_path)
        print(f"[{i+1}/{len(sampled_img_paths)}] Processing: {image_name}")

        # Encode same image with both encoders
        image_emb_b16, _ = encode_image_b16(img_path)
        image_emb_b32, _ = encode_image_b32(img_path)

        image_emb_b16 = image_emb_b16.squeeze(0)
        image_emb_b32 = image_emb_b32.squeeze(0)

        # Retrieve using B/16
        retrieved_b16 = retrieve_topk_captions_for_image(
            image_emb=image_emb_b16,
            caption_embs=caption_embs_b16,
            captions=captions,
            caption_image_names=caption_image_names,
            k=k
        )

        # Retrieve using B/32
        retrieved_b32 = retrieve_topk_captions_for_image(
            image_emb=image_emb_b32,
            caption_embs=caption_embs_b32,
            captions=captions,
            caption_image_names=caption_image_names,
            k=k
        )

        retrieved_caps_b16 = [(x["score"], x["caption"]) for x in retrieved_b16]
        retrieved_caps_b32 = [(x["score"], x["caption"]) for x in retrieved_b32]

        retrieved_names_b16 = [x["caption_image_name"] for x in retrieved_b16]
        retrieved_names_b32 = [x["caption_image_name"] for x in retrieved_b32]

        # Optional retrieval hit info
        hit5_b16 = int(any(name == image_name for name in retrieved_names_b16[:5]))
        hit5_b32 = int(any(name == image_name for name in retrieved_names_b32[:5]))

        # Generate with same Phi model, different retrieved context
        raw_b16, ans_b16 = generate_with_rag_phi(
            img_path=img_path,
            retrieved_caps=retrieved_caps_b16,
            phi_model=phi_model,
            processor=processor
        )

        raw_b32, ans_b32 = generate_with_rag_phi(
            img_path=img_path,
            retrieved_caps=retrieved_caps_b32,
            phi_model=phi_model,
            processor=processor
        )

        outputs.append({
            "image_name": image_name,
            "image_path": img_path,

            "retrieved_captions_b16": [x["caption"] for x in retrieved_b16],
            "retrieved_scores_b16": [x["score"] for x in retrieved_b16],
            "retrieved_image_names_b16": retrieved_names_b16,
            "hit@5_b16": hit5_b16,
            "raw_b16": raw_b16,
            "answer_b16": ans_b16,

            "retrieved_captions_b32": [x["caption"] for x in retrieved_b32],
            "retrieved_scores_b32": [x["score"] for x in retrieved_b32],
            "retrieved_image_names_b32": retrieved_names_b32,
            "hit@5_b32": hit5_b32,
            "raw_b32": raw_b32,
            "answer_b32": ans_b32
        })

        if (i + 1) % save_every == 0 or (i + 1) == len(sampled_img_paths):
            pd.DataFrame(outputs).to_csv(save_path, index=False)
            print(f"Saved to {save_path} at {i+1} samples")

    return pd.DataFrame(outputs)

In [27]:
caption_image_names = cap_df["image_name"].astype(str).tolist()

In [28]:
df_encoders = run_encoder16_vs_encoder32_rag_pipeline(
    img_dir=IMG_DIR,
    caption_embs_b16=caption_embs_b16,
    caption_embs_b32=caption_embs_b32,
    captions=captions,
    caption_image_names=caption_image_names,
    phi_model=phi_model,
    phi_processor=processor,
    num_samples=500,
    seed=123,
    k=5,
    save_every=50,
    save_path="/kaggle/working/encoder16_vs_encoder32_rag_500.csv"
)

df_encoders.head()

The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.

[1/500] Processing: 3202798691.jpg

WARNING:transformers_modules.microsoft.Phi-3.5-vision-instruct.12b77fb40b63a2c73c68243d3f767aab688a1b2a.modeling_phi3_v:You are not running the flash-attention implementation, expect numerical differences.

[2/500] Processing: 4888378326.jpg
[3/500] Processing: 4196910882.jpg
[4/500] Processing: 2437917174.jpg
[5/500] Processing: 3246788996.jpg
[6/500] Processing: 1507563902.jpg
[7/500] Processing: 4756096577.jpg
[8/500] Processing: 2705888144.jpg
[9/500] Processing: 4636627093.jpg
[10/500] Processing: 9726060.jpg
[11/500] Processing: 633456174.jpg
[12/500] Processing: 411175971.jpg
[13/500] Processing: 3694093650.jpg
[14/500] Processing: 3591094476.jpg
[15/500] Processing: 1918894054.jpg
[16/500] Processing: 439569646.jpg
[17/500] Processing: 512761651.jpg
[18/500] Processing: 531347711.jpg
[19/500] Processing: 5651514000.jpg
[20/500] Processing: 3265209567.jpg
[21/500] Processing: 7249180494.jpg
[22/500] Processing: 4329159924.jpg
[23/500] Processing: 4477151562.jpg
[24/500] Processing: 2905975229.jpg
[25/500] Processing: 52226520.jpg
[26/500] Processing: 8038838476.jpg
[27/500] Processing: 7001949951.jpg
[28/500] Processing: 2908391223.jpg
[29/500] Processing: 3057497487.jpg
[30/500] Processing: 4929731785.jpg
[31/500] Processing: 4538960982.jpg
[32/500] Processing: 6867197342.jpg
[33/500] Processing: 6082254728.jpg
[34/500] Processing: 2906759254.jpg
[35/500] Processing: 2507431891.jpg
[36/500] Processing: 331023909.jpg
[37/500] Processing: 467658231.jpg
[38/500] Processing: 4556002396.jpg
[39/500] Processing: 3225058391.jpg
[40/500] Processing: 4717966711.jpg
[41/500] Processing: 6887014469.jpg
[42/500] Processing: 4074803780.jpg
[43/500] Processing: 3444982197.jpg
[44/500] Processing: 1806580620.jpg
[45/500] Processing: 1105137588.jpg
[46/500] Processing: 2656110989.jpg
[47/500] Processing: 7576330234.jpg
[48/500] Processing: 4942012087.jpg
[49/500] Processing: 2609133063.jpg
[50/500] Processing: 3336374196.jpg
Saved to /kaggle/working/encoder16_vs_encoder32_rag_500.csv at 50 samples
[51/500] Processing: 4718615348.jpg
[52/500] Processing: 5635975939.jpg
[53/500] Processing: 3574962735.jpg
[54/500] Processing: 3251648670.jpg
[55/500] Processing: 3487820317.jpg
[56/500] Processing: 3698944019.jpg
[57/500] Processing: 4168954238.jpg
[58/500] Processing: 5807099586.jpg
[59/500] Processing: 4961508842.jpg
[60/500] Processing: 3302986588.jpg
[61/500] Processing: 6953298252.jpg
[62/500] Processing: 4103240621.jpg
[63/500] Processing: 367248403.jpg
[64/500] Processing: 233581449.jpg
[65/500] Processing: 2766926202.jpg
[66/500] Processing: 44201115.jpg
[67/500] Processing: 3264464625.jpg
[68/500] Processing: 4086326509.jpg
[69/500] Processing: 2378149488.jpg
[70/500] Processing: 4859789355.jpg
[71/500] Processing: 345684566.jpg
[72/500] Processing: 5622966650.jpg
[73/500] Processing: 4727583716.jpg
[74/500] Processing: 7754829172.jpg
[75/500] Processing: 2788183053.jpg
[76/500] Processing: 2686141763.jpg
[77/500] Processing: 7428316382.jpg
[78/500] Processing: 2236895638.jpg
[79/500] Processing: 5648321.jpg
[80/500] Processing: 511400700.jpg
[81/500] Processing: 7779718252.jpg
[82/500] Processing: 4724995701.jpg
[83/500] Processing: 3825049160.jpg
[84/500] Processing: 4744759921.jpg
[85/500] Processing: 6954663021.jpg
[86/500] Processing: 2867460039.jpg
[87/500] Processing: 4796827555.jpg
[88/500] Processing: 401649634.jpg
[89/500] Processing: 3234375022.jpg
[90/500] Processing: 2631353232.jpg
[91/500] Processing: 4319855412.jpg
[92/500] Processing: 4566219691.jpg
[93/500] Processing: 64086350.jpg
[94/500] Processing: 4845542946.jpg
[95/500] Processing: 1660269454.jpg
[96/500] Processing: 3109124656.jpg
[97/500] Processing: 3193029429.jpg
[98/500] Processing: 4694601786.jpg
[99/500] Processing: 6198563920.jpg
[100/500] Processing: 4347559524.jpg
Saved to /kaggle/working/encoder16_vs_encoder32_rag_500.csv at 100 samples
[101/500] Processing: 3827161885.jpg
[102/500] Processing: 4445607388.jpg
[103/500] Processing: 3469584002.jpg
[104/500] Processing: 356478206.jpg
[105/500] Processing: 370614351.jpg
[106/500] Processing: 85519095.jpg
[107/500] Processing: 2708775214.jpg
[108/500] Processing: 3565917449.jpg
[109/500] Processing: 311380477.jpg
[110/500] Processing: 56012054.jpg
[111/500] Processing: 7411114322.jpg
[112/500] Processing: 4623878206.jpg
[113/500] Processing: 2063399864.jpg
[114/500] Processing: 4327514739.jpg
[115/500] Processing: 3214333978.jpg
[116/500] Processing: 2359100647.jpg
[117/500] Processing: 3668900592.jpg
[118/500] Processing: 2542299880.jpg
[119/500] Processing: 513831663.jpg
[120/500] Processing: 365504466.jpg
[121/500] Processing: 7345543488.jpg
[122/500] Processing: 4860806028.jpg
[123/500] Processing: 4540109233.jpg
[124/500] Processing: 2279416167.jpg
[125/500] Processing: 4062486051.jpg
[126/500] Processing: 3329961466.jpg
[127/500] Processing: 5068219705.jpg
[128/500] Processing: 2094076980.jpg
[129/500] Processing: 3249278583.jpg
[130/500] Processing: 3197917064.jpg
[131/500] Processing: 2097398349.jpg
[132/500] Processing: 4926723.jpg
[133/500] Processing: 3748039603.jpg
[134/500] Processing: 4811455038.jpg
[135/500] Processing: 6848901011.jpg
[136/500] Processing: 316577571.jpg
[137/500] Processing: 2394003437.jpg
[138/500] Processing: 45935254.jpg
[139/500] Processing: 4892334228.jpg
[140/500] Processing: 4115212373.jpg
[141/500] Processing: 7102120965.jpg
[142/500] Processing: 4587901777.jpg
[143/500] Processing: 2737097000.jpg
[144/500] Processing: 3162442331.jpg
[145/500] Processing: 4455065396.jpg
[146/500] Processing: 1874617189.jpg
[147/500] Processing: 6307540579.jpg
[148/500] Processing: 4429660.jpg
[149/500] Processing: 3188587858.jpg
[150/500] Processing: 758921886.jpg
Saved to /kaggle/working/encoder16_vs_encoder32_rag_500.csv at 150 samples
[151/500] Processing: 4645242031.jpg
[152/500] Processing: 4732894483.jpg
[153/500] Processing: 2577450794.jpg
[154/500] Processing: 3689150386.jpg
[155/500] Processing: 3393152604.jpg
[156/500] Processing: 5491397203.jpg
[157/500] Processing: 2659606300.jpg
[158/500] Processing: 4937760948.jpg
[159/500] Processing: 58727908.jpg
[160/500] Processing: 191488669.jpg
[161/500] Processing: 3253257881.jpg
[162/500] Processing: 2407865161.jpg
[163/500] Processing: 4983959726.jpg
[164/500] Processing: 430803349.jpg
[165/500] Processing: 5220940345.jpg
[166/500] Processing: 3401437960.jpg
[167/500] Processing: 218096711.jpg
[168/500] Processing: 295402802.jpg
[169/500] Processing: 171134073.jpg
[170/500] Processing: 4717261252.jpg
[171/500] Processing: 4771148918.jpg
[172/500] Processing: 1043910339.jpg
[173/500] Processing: 543363241.jpg
[174/500] Processing: 4037128007.jpg
[175/500] Processing: 4469010721.jpg
[176/500] Processing: 2830073704.jpg
[177/500] Processing: 3590049329.jpg
[178/500] Processing: 4968714648.jpg
[179/500] Processing: 3555376013.jpg
[180/500] Processing: 4027160843.jpg
[181/500] Processing: 1299817309.jpg
[182/500] Processing: 1065323785.jpg
[183/500] Processing: 6857882214.jpg
[184/500] Processing: 4654264126.jpg
[185/500] Processing: 3397090388.jpg
[186/500] Processing: 1255846277.jpg
[187/500] Processing: 476765164.jpg
[188/500] Processing: 1196432301.jpg
[189/500] Processing: 2603792708.jpg
[190/500] Processing: 4937201390.jpg
[191/500] Processing: 3613424631.jpg
[192/500] Processing: 51900752.jpg
[193/500] Processing: 2858835419.jpg
[194/500] Processing: 2618322793.jpg
[195/500] Processing: 7425257042.jpg
[196/500] Processing: 8220955383.jpg
[197/500] Processing: 4560100704.jpg
[198/500] Processing: 4718118294.jpg
[199/500] Processing: 2173677067.jpg
[200/500] Processing: 4571650064.jpg
Saved to /kaggle/working/encoder16_vs_encoder32_rag_500.csv at 200 samples
[201/500] Processing: 4664359066.jpg
[202/500] Processing: 137430967.jpg
[203/500] Processing: 3177298173.jpg
[204/500] Processing: 3094568845.jpg
[205/500] Processing: 190634565.jpg
[206/500] Processing: 3275575996.jpg
[207/500] Processing: 1262583859.jpg
[208/500] Processing: 3335296184.jpg
[209/500] Processing: 404850242.jpg
[210/500] Processing: 3049092854.jpg
[211/500] Processing: 110671345.jpg
[212/500] Processing: 7774468390.jpg
[213/500] Processing: 5721131714.jpg
[214/500] Processing: 5829317322.jpg
[215/500] Processing: 289599470.jpg
[216/500] Processing: 519524552.jpg
[217/500] Processing: 4379493825.jpg
[218/500] Processing: 3226411414.jpg
[219/500] Processing: 136645716.jpg
[220/500] Processing: 7817889978.jpg
[221/500] Processing: 3793619579.jpg
[222/500] Processing: 209803062.jpg
[223/500] Processing: 109608573.jpg
[224/500] Processing: 305611825.jpg
[225/500] Processing: 3838585113.jpg
[226/500] Processing: 2856700531.jpg
[227/500] Processing: 2410153942.jpg
[228/500] Processing: 3541915243.jpg
[229/500] Processing: 122958692.jpg
[230/500] Processing: 2342478660.jpg
[231/500] Processing: 5457465605.jpg
[232/500] Processing: 4449702874.jpg
[233/500] Processing: 2376878930.jpg
[234/500] Processing: 3569979711.jpg
[235/500] Processing: 4470113445.jpg
[236/500] Processing: 2058989634.jpg
[237/500] Processing: 3199895624.jpg
[238/500] Processing: 234241682.jpg
[239/500] Processing: 217949158.jpg
[240/500] Processing: 3642604708.jpg
[241/500] Processing: 4716333601.jpg
[242/500] Processing: 5064970423.jpg
[243/500] Processing: 3050606344.jpg
[244/500] Processing: 275858550.jpg
[245/500] Processing: 4852300027.jpg
[246/500] Processing: 2282573692.jpg
[247/500] Processing: 3340575518.jpg
[248/500] Processing: 2341850464.jpg
[249/500] Processing: 4973604926.jpg
[250/500] Processing: 380041023.jpg
Saved to /kaggle/working/encoder16_vs_encoder32_rag_500.csv at 250 samples
[251/500] Processing: 281297361.jpg
[252/500] Processing: 5767811093.jpg
[253/500] Processing: 4850814517.jpg
[254/500] Processing: 8091220380.jpg
[255/500] Processing: 3599568766.jpg
[256/500] Processing: 81370406.jpg
[257/500] Processing: 3367399.jpg
[258/500] Processing: 1998457059.jpg
[259/500] Processing: 87761964.jpg
[260/500] Processing: 4388402668.jpg
[261/500] Processing: 2109280562.jpg
[262/500] Processing: 55473406.jpg
[263/500] Processing: 4963468841.jpg
[264/500] Processing: 485921585.jpg
[265/500] Processing: 4826833243.jpg
[266/500] Processing: 4069607034.jpg
[267/500] Processing: 1424237335.jpg
[268/500] Processing: 2406591500.jpg
[269/500] Processing: 724056172.jpg
[270/500] Processing: 3052440932.jpg
[271/500] Processing: 2900242501.jpg
[272/500] Processing: 109544260.jpg
[273/500] Processing: 2360310311.jpg
[274/500] Processing: 241347496.jpg
[275/500] Processing: 2533414541.jpg
[276/500] Processing: 6928014516.jpg
[277/500] Processing: 3798552554.jpg
[278/500] Processing: 6320721815.jpg
[279/500] Processing: 2600950267.jpg
[280/500] Processing: 114939325.jpg
[281/500] Processing: 2605373150.jpg
[282/500] Processing: 2661641497.jpg
[283/500] Processing: 5602737557.jpg
[284/500] Processing: 4920897810.jpg
[285/500] Processing: 60617980.jpg
[286/500] Processing: 3301854980.jpg
[287/500] Processing: 1552467862.jpg
[288/500] Processing: 516761840.jpg
[289/500] Processing: 6953886164.jpg
[290/500] Processing: 4441980889.jpg
[291/500] Processing: 2141713971.jpg
[292/500] Processing: 6332487919.jpg
[293/500] Processing: 4770171876.jpg
[294/500] Processing: 4689253216.jpg
[295/500] Processing: 4981184852.jpg
[296/500] Processing: 3191805046.jpg
[297/500] Processing: 49402821.jpg
[298/500] Processing: 4766215198.jpg
[299/500] Processing: 206647555.jpg
[300/500] Processing: 3688364166.jpg
Saved to /kaggle/working/encoder16_vs_encoder32_rag_500.csv at 300 samples
[301/500] Processing: 2308352490.jpg
[302/500] Processing: 2712974062.jpg
[303/500] Processing: 179620911.jpg
[304/500] Processing: 2887614578.jpg
[305/500] Processing: 5330858932.jpg
[306/500] Processing: 4564193650.jpg
[307/500] Processing: 3631344685.jpg
[308/500] Processing: 3040051410.jpg
[309/500] Processing: 5405152538.jpg
[310/500] Processing: 533363682.jpg
[311/500] Processing: 4456432456.jpg
[312/500] Processing: 908636680.jpg
[313/500] Processing: 3294717824.jpg
[314/500] Processing: 2203224077.jpg
[315/500] Processing: 5280521648.jpg
[316/500] Processing: 194464865.jpg
[317/500] Processing: 86289696.jpg
[318/500] Processing: 558161347.jpg
[319/500] Processing: 3436395540.jpg
[320/500] Processing: 5169120032.jpg
[321/500] Processing: 2594902417.jpg
[322/500] Processing: 4445556418.jpg
[323/500] Processing: 3305107222.jpg
[324/500] Processing: 5903545909.jpg
[325/500] Processing: 25817944.jpg
[326/500] Processing: 3438060110.jpg
[327/500] Processing: 3611925069.jpg
[328/500] Processing: 4872377897.jpg
[329/500] Processing: 189022647.jpg
[330/500] Processing: 4728136795.jpg
[331/500] Processing: 3475751336.jpg
[332/500] Processing: 2057305043.jpg
[333/500] Processing: 7002180750.jpg
[334/500] Processing: 3157220149.jpg
[335/500] Processing: 4780491039.jpg
[336/500] Processing: 4801647530.jpg
[337/500] Processing: 1629314152.jpg
[338/500] Processing: 421762505.jpg
[339/500] Processing: 3146232740.jpg
[340/500] Processing: 2267819545.jpg
[341/500] Processing: 2920005017.jpg
[342/500] Processing: 3155501473.jpg
[343/500] Processing: 5019568325.jpg
[344/500] Processing: 2807177340.jpg
[345/500] Processing: 199412869.jpg
[346/500] Processing: 1247181182.jpg
[347/500] Processing: 2868652721.jpg
[348/500] Processing: 8003613232.jpg
[349/500] Processing: 293575531.jpg
[350/500] Processing: 6251875212.jpg
Saved to /kaggle/working/encoder16_vs_encoder32_rag_500.csv at 350 samples
[351/500] Processing: 5196783191.jpg
[352/500] Processing: 4756001275.jpg
[353/500] Processing: 2666078276.jpg
[354/500] Processing: 514990193.jpg
[355/500] Processing: 4804607632.jpg
[356/500] Processing: 4826619341.jpg
[357/500] Processing: 5739363696.jpg
[358/500] Processing: 6629925875.jpg
[359/500] Processing: 1465531335.jpg
[360/500] Processing: 1394620454.jpg
[361/500] Processing: 3685373706.jpg
[362/500] Processing: 2633069263.jpg
[363/500] Processing: 2957561476.jpg
[364/500] Processing: 4586925517.jpg
[365/500] Processing: 2319087586.jpg
[366/500] Processing: 4011394505.jpg
[367/500] Processing: 6970752746.jpg
[368/500] Processing: 4905392047.jpg
[369/500] Processing: 4803984649.jpg
[370/500] Processing: 403844559.jpg
[371/500] Processing: 534570169.jpg
[372/500] Processing: 2883324329.jpg
[373/500] Processing: 3677613006.jpg
[374/500] Processing: 2794605643.jpg
[375/500] Processing: 2092922849.jpg
[376/500] Processing: 6184114561.jpg
[377/500] Processing: 2124547387.jpg
[378/500] Processing: 3538686658.jpg
[379/500] Processing: 2248395289.jpg
[380/500] Processing: 2528076469.jpg
[381/500] Processing: 4864024799.jpg
[382/500] Processing: 1285067106.jpg
[383/500] Processing: 4564320256.jpg
[384/500] Processing: 675153.jpg
[385/500] Processing: 434938585.jpg
[386/500] Processing: 498951987.jpg
[387/500] Processing: 4612142419.jpg
[388/500] Processing: 2536943209.jpg
[389/500] Processing: 2902661518.jpg
[390/500] Processing: 731236273.jpg
[391/500] Processing: 4701385015.jpg
[392/500] Processing: 365128300.jpg
[393/500] Processing: 4506417051.jpg
[394/500] Processing: 3234401637.jpg
[395/500] Processing: 339822505.jpg
[396/500] Processing: 4727371226.jpg
[397/500] Processing: 5105522629.jpg
[398/500] Processing: 4679254513.jpg
[399/500] Processing: 3704642429.jpg
[400/500] Processing: 3292124758.jpg
Saved to /kaggle/working/encoder16_vs_encoder32_rag_500.csv at 400 samples
[401/500] Processing: 2382326464.jpg
[402/500] Processing: 511819129.jpg
[403/500] Processing: 527946505.jpg
[404/500] Processing: 2481490320.jpg
[405/500] Processing: 6879494312.jpg
[406/500] Processing: 5641021474.jpg
[407/500] Processing: 4933865159.jpg
[408/500] Processing: 2152070348.jpg
[409/500] Processing: 4046071738.jpg
[410/500] Processing: 522183263.jpg
[411/500] Processing: 4747892933.jpg
[412/500] Processing: 2536881159.jpg
[413/500] Processing: 2249094622.jpg
[414/500] Processing: 9556225.jpg
[415/500] Processing: 4054989083.jpg
[416/500] Processing: 3508413697.jpg
[417/500] Processing: 3173461705.jpg
[418/500] Processing: 1408958345.jpg
[419/500] Processing: 314454989.jpg
[420/500] Processing: 3821671043.jpg
[421/500] Processing: 2695085862.jpg
[422/500] Processing: 6685838035.jpg
[423/500] Processing: 423375604.jpg
[424/500] Processing: 361831875.jpg
[425/500] Processing: 1618094569.jpg
[426/500] Processing: 2746877062.jpg
[427/500] Processing: 480858814.jpg
[428/500] Processing: 493507605.jpg
[429/500] Processing: 50158447.jpg
[430/500] Processing: 2771214516.jpg
[431/500] Processing: 3935633359.jpg
[432/500] Processing: 325015111.jpg
[433/500] Processing: 4467431522.jpg
[434/500] Processing: 1020651753.jpg
[435/500] Processing: 4479587916.jpg
[436/500] Processing: 4773227009.jpg
[437/500] Processing: 2839532455.jpg
[438/500] Processing: 4987363775.jpg
[439/500] Processing: 4100783560.jpg
[440/500] Processing: 566397227.jpg
[441/500] Processing: 1394368714.jpg
[442/500] Processing: 2937882774.jpg
[443/500] Processing: 3208032657.jpg
[444/500] Processing: 3697902123.jpg
[445/500] Processing: 3136437458.jpg
[446/500] Processing: 4702844775.jpg
[447/500] Processing: 2879241506.jpg
[448/500] Processing: 3441959314.jpg
[449/500] Processing: 405615014.jpg
[450/500] Processing: 8138745455.jpg
Saved to /kaggle/working/encoder16_vs_encoder32_rag_500.csv at 450 samples
[451/500] Processing: 207225205.jpg
[452/500] Processing: 7498045028.jpg
[453/500] Processing: 1412832223.jpg
[454/500] Processing: 3686924335.jpg
[455/500] Processing: 4802552043.jpg
[456/500] Processing: 3400082864.jpg
[457/500] Processing: 3595992258.jpg
[458/500] Processing: 4750874600.jpg
[459/500] Processing: 537069478.jpg
[460/500] Processing: 3520617304.jpg
[461/500] Processing: 541537091.jpg
[462/500] Processing: 3970646119.jpg
[463/500] Processing: 5972486972.jpg
[464/500] Processing: 4621393910.jpg
[465/500] Processing: 307327914.jpg
[466/500] Processing: 2037264035.jpg
[467/500] Processing: 4650780114.jpg
[468/500] Processing: 4187922589.jpg
[469/500] Processing: 3484841598.jpg
[470/500] Processing: 6963176832.jpg
[471/500] Processing: 3549140234.jpg
[472/500] Processing: 358127240.jpg
[473/500] Processing: 4633639059.jpg
[474/500] Processing: 3286193613.jpg
[475/500] Processing: 3225984916.jpg
[476/500] Processing: 2607861348.jpg
[477/500] Processing: 6161478369.jpg
[478/500] Processing: 1441148458.jpg
[479/500] Processing: 3339768802.jpg
[480/500] Processing: 4029918745.jpg
[481/500] Processing: 484896012.jpg
[482/500] Processing: 2370221025.jpg
[483/500] Processing: 2773331947.jpg
[484/500] Processing: 1400424834.jpg
[485/500] Processing: 2656749876.jpg
[486/500] Processing: 2423277850.jpg
[487/500] Processing: 2547957252.jpg
[488/500] Processing: 3834502656.jpg
[489/500] Processing: 428506573.jpg
[490/500] Processing: 260029153.jpg
[491/500] Processing: 3644941648.jpg
[492/500] Processing: 4446013212.jpg
[493/500] Processing: 4645546686.jpg
[494/500] Processing: 2604332654.jpg
[495/500] Processing: 4556897985.jpg
[496/500] Processing: 3417672954.jpg
[497/500] Processing: 3328324395.jpg
[498/500] Processing: 2533642917.jpg
[499/500] Processing: 6790868526.jpg
[500/500] Processing: 3027399066.jpg
Saved to /kaggle/working/encoder16_vs_encoder32_rag_500.csv at 500 samples

,image_name,image_path,retrieved_captions_b16,retrieved_scores_b16,retrieved_image_names_b16,hit@5_b16,raw_b16,answer_b16,retrieved_captions_b32,retrieved_scores_b32,retrieved_image_names_b32,hit@5_b32,raw_b32,answer_b32
0,3202798691.jpg,/kaggle/input/datasets/hsankesara/flickr-image...,[ A small child rides a bicycle on the side of...,"[0.32265743613243103, 0.29817506670951843, 0.2...","[4674933591.jpg, 2308108566.jpg, 2320420111.jp...",0,A man rides a bike on a dirt road past a blue ...,A man rides a bike on a dirt road past a blue ...,"[ A man rides a bike on a dirt path ., A man ...","[0.3402847945690155, 0.334036648273468, 0.3295...","[2308108566.jpg, 6150843883.jpg, 2778696039.jp...",0,A man rides a bike on a dirt path.,A man rides a bike on a dirt path.
1,4888378326.jpg,/kaggle/input/datasets/hsankesara/flickr-image...,[ A group of friends seated on concrete waitin...,"[0.37924468517303467, 0.3555122911930084, 0.33...","[137431115.jpg, 137431115.jpg, 3432634159.jpg,...",0,A group of men are sitting on the ledges of a ...,A group of men are sitting on the ledges of a ...,[ A group of friends seated on concrete waitin...,"[0.38841867446899414, 0.34602299332618713, 0.3...","[137431115.jpg, 4621091937.jpg, 984950.jpg, 22...",0,A group of men are sitting on the ledges of a ...,A group of men are sitting on the ledges of a ...
2,4196910882.jpg,/kaggle/input/datasets/hsankesara/flickr-image...,[ A band is playing on stage with the guy on t...,"[0.3219168782234192, 0.31107383966445923, 0.30...","[2322797357.jpg, 7094400667.jpg, 2260099785.jp...",0,Two men are on stage playing guitars while a t...,Two men are on stage playing guitars while a t...,[ A band is playing on stage with the guy on t...,"[0.3466407060623169, 0.3399950861930847, 0.338...","[2322797357.jpg, 2260099785.jpg, 2351694146.jp...",0,Two men are playing their guitars and singing ...,Two men are playing their guitars and singing ...
3,2437917174.jpg,/kaggle/input/datasets/hsankesara/flickr-image...,[ A girl in a white sweater and blue jeans typ...,"[0.2959112823009491, 0.29172879457473755, 0.28...","[3139289763.jpg, 4304306426.jpg, 244344740.jpg...",0,A young woman is at her desk working on what a...,A young woman is at her desk working on what a...,[ A young woman is at her desk working on what...,"[0.3313107490539551, 0.31625914573669434, 0.31...","[244344740.jpg, 4304306426.jpg, 2437917174.jpg...",1,A young woman is at her desk writing on a piec...,A young woman is at her desk writing on a piec...
4,3246788996.jpg,/kaggle/input/datasets/hsankesara/flickr-image...,[ Several people paying attention to a lecture...,"[0.2974925637245178, 0.29462748765945435, 0.29...","[428168186.jpg, 2766744325.jpg, 72008635.jpg, ...",0,Several people paying attention to a lecture.,Several people paying attention to a lecture.,[ A group of people pointing and looking at so...,"[0.3177132308483124, 0.3125268816947937, 0.309...","[3501386648.jpg, 3099294440.jpg, 3971388640.jp...",0,A group of people pointing and looking at some...,A group of people pointing and looking at some...

### Analyzing the output quality of the answers obtained in both the cases

In [29]:
from collections import defaultdict

gt_map = defaultdict(list)
for _, row in df.iterrows():
    gt_map[str(row["image_name"]).strip()].append(str(row["comment"]).strip())

df_encoders["references"] = df_encoders["image_name"].map(gt_map)
df_eval_encoders = df_encoders[df_encoders["references"].notna()].copy()

In [30]:
import numpy as np
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

smooth = SmoothingFunction().method1
rouge = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

def bleu_against_refs(pred, refs):
    pred_tokens = pred.split()
    ref_tokens = [r.split() for r in refs]
    return sentence_bleu(ref_tokens, pred_tokens, smoothing_function=smooth)

def best_rouge_against_refs(pred, refs):
    best = {"rouge1": 0.0, "rouge2": 0.0, "rougeL": 0.0}
    for ref in refs:
        scores = rouge.score(ref, pred)
        for k in best:
            best[k] = max(best[k], scores[k].fmeasure)
    return best

In [31]:
@torch.no_grad()
def compute_clipscore_single(img_path, caption):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess_b32(img).unsqueeze(0).to(device)

    img_feat = clip_model_b32.encode_image(img_in)
    img_feat = img_feat / img_feat.norm(dim=-1, keepdim=True)

    tokens = open_clip.tokenize([caption]).to(device)
    txt_feat = clip_model_b32.encode_text(tokens)
    txt_feat = txt_feat / txt_feat.norm(dim=-1, keepdim=True)

    return (img_feat * txt_feat).sum(dim=-1).item()

In [32]:
def evaluate_model_outputs(df_eval, answer_col):
    bleu_scores = []
    rouge1_scores, rouge2_scores, rougeL_scores = [], [], []
    clip_scores = []

    for _, row in df_eval.iterrows():
        refs = row["references"]
        pred = str(row[answer_col]).strip()

        bleu_scores.append(bleu_against_refs(pred, refs))

        rs = best_rouge_against_refs(pred, refs)
        rouge1_scores.append(rs["rouge1"])
        rouge2_scores.append(rs["rouge2"])
        rougeL_scores.append(rs["rougeL"])

        clip_scores.append(compute_clipscore_single(row["image_path"], pred))

    return {
        "BLEU": bleu_scores,
        "ROUGE-1": rouge1_scores,
        "ROUGE-2": rouge2_scores,
        "ROUGE-L": rougeL_scores,
        "CLIPScore": clip_scores
    }

In [33]:
scores_b16 = evaluate_model_outputs(df_eval_encoders, "answer_b16")
scores_b32 = evaluate_model_outputs(df_eval_encoders, "answer_b32")

In [34]:
def build_encoder_summary(scores1, scores2, name1="ViT-B/16", name2="ViT-B/32"):
    rows = []

    for metric in ["BLEU", "ROUGE-1", "ROUGE-2", "ROUGE-L", "CLIPScore"]:
        s1 = np.array(scores1[metric])
        s2 = np.array(scores2[metric])

        rows.append({
            "Metric": metric,
            name1: f"{s1.mean():.4f} ± {s1.std():.4f}",
            name2: f"{s2.mean():.4f} ± {s2.std():.4f}",
            "Gain (B16-B32)": s1.mean() - s2.mean()
        })

    return pd.DataFrame(rows)

In [35]:
summary_encoders = build_encoder_summary(
    scores_b16,
    scores_b32,
    name1="ViT-B/16",
    name2="ViT-B/32"
)

summary_encoders

      Metric         ViT-B/16         ViT-B/32  Gain (B16-B32)
0       BLEU  0.2473 ± 0.2748  0.2554 ± 0.2768       -0.008090
1    ROUGE-1  0.5651 ± 0.2181  0.5618 ± 0.2213        0.003278
2    ROUGE-2  0.3529 ± 0.2879  0.3508 ± 0.2926        0.002113
3    ROUGE-L  0.5351 ± 0.2308  0.5308 ± 0.2352        0.004210
4  CLIPScore  0.3143 ± 0.0424  0.3267 ± 0.0352       -0.012397

### Conducting paired significance test to see whether the result is significant

In [36]:
!pip install scipy

Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from scipy) (2.0.2)

In [37]:
from scipy.stats import ttest_rel

def paired_significance_test(scores1, scores2, name1="ViT-B/16", name2="ViT-B/32"):
    rows = []

    for metric in ["BLEU", "ROUGE-1", "ROUGE-2", "ROUGE-L", "CLIPScore"]:
        stat, pval = ttest_rel(scores1[metric], scores2[metric])

        rows.append({
            "Metric": metric,
            "p-value": pval,
            "Significant (<0.05)": pval < 0.05
        })

    return pd.DataFrame(rows)

In [38]:
ttest_encoders = paired_significance_test(
    scores_b16,
    scores_b32,
    name1="ViT-B/16",
    name2="ViT-B/32"
)

ttest_encoders

      Metric       p-value  Significant (<0.05)
0       BLEU  4.480745e-01                False
1    ROUGE-1  7.004362e-01                False
2    ROUGE-2  8.483155e-01                False
3    ROUGE-L  6.349323e-01                False
4  CLIPScore  2.645738e-12                 True

In [39]:
summary_encoders.to_csv("/kaggle/working/summary_encoder16_vs_encoder32.csv", index=False)
ttest_encoders.to_csv("/kaggle/working/ttest_encoder16_vs_encoder32.csv", index=False)
df_eval_encoders.to_csv("/kaggle/working/df_eval_encoder16_vs_encoder32.csv", index=False)