In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O

In [2]:
!pip uninstall -y transformers accelerate -q
!pip install -q transformers==4.43.0 accelerate==0.30.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 72.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 kB 21.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 39.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 90.6 MB/s eta 0:00:00

### Importing the validation set of MSCOCO(5000 images)

In [3]:
import os

BASE = "/kaggle/input/datasets/saptarshim596/val2017-ms-coco/val2017"
IMG_DIR = os.path.join(BASE, "val2017")
CAPTION_FILE = "/kaggle/input/datasets/saptarshim596/val2017-ms-coco/coco_captions.csv"

print("Image folder:", IMG_DIR)
print("Caption file:", CAPTION_FILE)

Image folder: /kaggle/input/datasets/saptarshim596/val2017-ms-coco/val2017/val2017
Caption file: /kaggle/input/datasets/saptarshim596/val2017-ms-coco/coco_captions.csv

In [4]:
print("Number of images:", len(os.listdir(IMG_DIR)))
print(os.listdir(IMG_DIR)[:10])

Number of images: 5000
['000000011197.jpg', '000000219485.jpg', '000000151000.jpg', '000000371677.jpg', '000000038825.jpg', '000000384527.jpg', '000000122969.jpg', '000000028809.jpg', '000000053505.jpg', '000000384513.jpg']

In [5]:
import pandas as pd

df = pd.read_csv(CAPTION_FILE, sep=',')
df.head()

         image_name                                            comment
0  000000179765.jpg  A black Honda motorcycle parked in front of a ...
1  000000179765.jpg      A Honda motorcycle parked in a grass driveway
2  000000190236.jpg  An office cubicle with four different types of...
3  000000331352.jpg          A small closed toilet in a cramped space.
4  000000517069.jpg     Two women waiting at a bench next to a street.

In [6]:
df.columns = df.columns.str.strip()

In [7]:
!pip -q install open_clip_torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 25.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 3.0 MB/s eta 0:00:00

In [8]:
import torch
import open_clip
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

clip_model, _, preprocess = open_clip.create_model_and_transforms(
    "ViT-B-32",
    pretrained="laion2b_s34b_b79k"
)
tokenizer = open_clip.get_tokenizer("ViT-B-32")

clip_model = clip_model.to(device).eval()
print("Device:", device)

open_clip_model.safetensors:   0%|          | 0.00/605M [00:00<?, ?B/s]

Device: cuda

In [9]:
CAPTION_N = 200000

cap_df = df.sample(n=min(CAPTION_N, len(df)), random_state=42).reset_index(drop=True)
captions = cap_df["comment"].astype(str).tolist()

print("Captions in pool:", len(captions))

Captions in pool: 25014

In [10]:
@torch.no_grad()
def encode_texts(text_list, batch_size=256):
    embs = []
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        tokens = tokenizer(batch).to(device)
        feat = clip_model.encode_text(tokens)
        feat = feat / feat.norm(dim=-1, keepdim=True)
        embs.append(feat.cpu())
    return torch.cat(embs, dim=0)

In [11]:
from PIL import Image
import matplotlib.pyplot as plt
import os, random

@torch.no_grad()
def encode_image(img_path):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess(img).unsqueeze(0).to(device)
    feat = clip_model.encode_image(img_in)
    feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.cpu(), img

In [12]:
import transformers, accelerate, torch
print(transformers.__version__)
print(accelerate.__version__)
print(torch.__version__)

4.43.0
0.30.0
2.9.0+cu126

### Setting up the LLM(Phi-3.5-vision-instruct) model

In [13]:
import os
import torch
from transformers import AutoConfig, AutoProcessor, AutoModelForCausalLM
from huggingface_hub import login

os.environ["HF_HOME"] = "/kaggle/working/hf_cache"
os.environ["TRANSFORMERS_CACHE"] = "/kaggle/working/hf_cache"

# Login
login(token="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")

VLM_NAME = "microsoft/Phi-3.5-vision-instruct"

config = AutoConfig.from_pretrained(
    VLM_NAME,
    trust_remote_code=True
)
config._attn_implementation = "eager"

processor = AutoProcessor.from_pretrained(
    VLM_NAME,
    trust_remote_code=True  
)

phi_model = AutoModelForCausalLM.from_pretrained(
    VLM_NAME,
    config=config,
    trust_remote_code=True,
    device_map="auto",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
).eval()

2026-04-05 15:04:40.616547: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1775401480.826063      24 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1775401480.880286      24 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1775401481.365570      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775401481.365596      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775401481.365599      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775401481.365602      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

config.json: 0.00B [00:00, ?B/s]

configuration_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- configuration_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

processor_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

processing_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- processing_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
/usr/local/lib/python3.12/dist-packages/transformers/models/auto/image_processing_auto.py:513: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(

preprocessor_config.json:   0%|          | 0.00/442 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/670 [00:00<?, ?B/s]

modeling_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- modeling_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.35G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/136 [00:00<?, ?B/s]

### Analysis of responses for hit@1, hit@5, hit@10

In [14]:
CAPTION_N = 200000

cap_df = df.sample(n=min(CAPTION_N, len(df)), random_state=42).reset_index(drop=True)

captions = cap_df["comment"].astype(str).tolist()

print("Captions in pool:", len(captions))

Captions in pool: 25014

In [15]:
@torch.no_grad()
def encode_captions(text_list, batch_size=256):
    embs = []

    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]

        tokens = open_clip.tokenize(batch).to(device)

        feat = clip_model.encode_text(tokens)

        # Normalize (important for cosine similarity)
        feat = feat / feat.norm(dim=-1, keepdim=True)

        embs.append(feat.cpu())

        if i % (batch_size * 10) == 0:
            print(f"Processed {i}/{len(text_list)} captions")

    return torch.cat(embs, dim=0)

In [16]:
caption_embs = encode_captions(captions, batch_size=256)

print("Caption embeddings:", caption_embs.shape)

Processed 0/25014 captions
Processed 2560/25014 captions
Processed 5120/25014 captions
Processed 7680/25014 captions
Processed 10240/25014 captions
Processed 12800/25014 captions
Processed 15360/25014 captions
Processed 17920/25014 captions
Processed 20480/25014 captions
Processed 23040/25014 captions
Caption embeddings: torch.Size([25014, 512])

In [17]:
import os
import random
import re
import torch
import pandas as pd
from PIL import Image


def clean_answer(text):
    text = text.strip()

    stop_markers = [
        "# User", "# Assistant", "# Input", "# Output", "##",
        "<|user|>", "<|assistant|>", "<|end|>"
    ]

    for marker in stop_markers:
        if marker in text:
            text = text.split(marker)[0].strip()

    sentences = re.split(r'(?<=[.!?])\s+', text)
    return " ".join(sentences[:1]).strip()


@torch.no_grad()
def encode_image(img_path):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess(img).unsqueeze(0).to(device)
    feat = clip_model.encode_image(img_in)
    feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.cpu(), img


def get_random_image_embeddings(img_dir, num_samples=10, seed=42):
    random.seed(seed)

    all_images = [
        os.path.join(img_dir, f)
        for f in os.listdir(img_dir)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    if not all_images:
        raise ValueError(f"No image files found in: {img_dir}")

    sampled_images = random.sample(all_images, min(num_samples, len(all_images)))

    embeddings = []
    image_objects = []
    image_paths = []

    for img_path in sampled_images:
        feat, img = encode_image(img_path)
        embeddings.append(feat)
        image_objects.append(img)
        image_paths.append(img_path)

    embeddings = torch.cat(embeddings, dim=0)   # (N, D)
    return embeddings, image_objects, image_paths

In [18]:
def retrieve_topk_captions_for_image(image_emb, caption_embs, captions, caption_image_names, k=10):
    """
    image_emb: tensor of shape (D,) or (1, D)
    caption_embs: tensor of shape (M, D)
    captions: list[str]
    caption_image_names: list[str]
    """
    if image_emb.dim() == 1:
        image_emb = image_emb.unsqueeze(0)

    sims = image_emb @ caption_embs.T
    top_scores, top_idx = torch.topk(sims, k=min(k, len(captions)), dim=1)

    results = []
    for score, idx in zip(top_scores[0].tolist(), top_idx[0].tolist()):
        results.append({
            "score": score,
            "caption": captions[idx],
            "caption_image_name": caption_image_names[idx]
        })

    return results

In [19]:

@torch.no_grad()
def generate_with_rag(img_path, retrieved_caps, phi_model, processor, max_new_tokens=25):
    image = Image.open(img_path).convert("RGB")

    context_block = "\n".join([f"- {cap}" for _, cap in retrieved_caps])

    prompt = f"""<|user|>
<|image_1|>
Describe this image in one sentence.

Helpful retrieved captions:
{context_block}

Only answer with the description sentence.
<|end|>
<|assistant|>
"""

    inputs = processor(
        text=prompt,
        images=image,
        return_tensors="pt"
    )

    for k, v in inputs.items():
        if hasattr(v, "to"):
            inputs[k] = v.to(phi_model.device)

    outputs = phi_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        use_cache=False,
        eos_token_id=processor.tokenizer.eos_token_id,
        pad_token_id=processor.tokenizer.eos_token_id
    )

    generated_ids = outputs[:, inputs["input_ids"].shape[1]:]

    raw_answer = processor.tokenizer.decode(
        generated_ids[0],
        skip_special_tokens=True
    ).strip()

    return raw_answer, clean_answer(raw_answer)

In [20]:
import os
import pandas as pd

def run_rag_quality_vs_recall_pipeline(
    img_dir,
    caption_embs,
    captions,
    caption_image_names,
    phi_model,
    processor,
    num_samples=100,
    seed=42,
    k=10,
    save_every=25,
    save_path="/kaggle/working/rag_quality_vs_recall_mscoco.csv"
):
    sampled_img_embs, _, sampled_img_paths = get_random_image_embeddings(
        img_dir,
        num_samples=num_samples,
        seed=seed
    )

    outputs = []

    for i, img_path in enumerate(sampled_img_paths):
        image_name = os.path.basename(img_path)
        print(f"[{i+1}/{len(sampled_img_paths)}] Processing: {image_name}")

        image_emb = sampled_img_embs[i]

        retrieved = retrieve_topk_captions_for_image(
            image_emb=image_emb,
            caption_embs=caption_embs,
            captions=captions,
            caption_image_names=caption_image_names,
            k=k
        )

        retrieved_caps = [(x["score"], x["caption"]) for x in retrieved]
        retrieved_names = [x["caption_image_name"] for x in retrieved]

        hit1 = int(any(name == image_name for name in retrieved_names[:1]))
        hit5 = int(any(name == image_name for name in retrieved_names[:5]))
        hit10 = int(any(name == image_name for name in retrieved_names[:10]))

        raw_rag, ans_rag = generate_with_rag(
            img_path=img_path,
            retrieved_caps=retrieved_caps,
            phi_model=phi_model,
            processor=processor
        )

        outputs.append({
            "image_name": image_name,
            "image_path": img_path,
            "retrieved_captions": [x["caption"] for x in retrieved],
            "retrieved_scores": [x["score"] for x in retrieved],
            "retrieved_image_names": retrieved_names,
            "hit@1": hit1,
            "hit@5": hit5,
            "hit@10": hit10,
            "raw_rag": raw_rag,
            "answer_rag": ans_rag
        })

        if (i + 1) % save_every == 0 or (i + 1) == len(sampled_img_paths):
            pd.DataFrame(outputs).to_csv(save_path, index=False)
            print(f"Saved to {save_path} at {i+1} samples")

    return pd.DataFrame(outputs)

In [21]:
caption_image_names = cap_df["image_name"].astype(str).tolist()

In [22]:
df_rag_recall = run_rag_quality_vs_recall_pipeline(
    img_dir=IMG_DIR,
    caption_embs=caption_embs,
    captions=captions,
    caption_image_names=caption_image_names,
    phi_model=phi_model,
    processor=processor,
    num_samples=200,
    seed=123,
    k=10,
    save_every=50,
    save_path="/kaggle/working/rag_quality_vs_recall_200.csv"
)

df_rag_recall.head()

The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.

[1/200] Processing: 000000328238.jpg

WARNING:transformers_modules.microsoft.Phi-3.5-vision-instruct.12b77fb40b63a2c73c68243d3f767aab688a1b2a.modeling_phi3_v:You are not running the flash-attention implementation, expect numerical differences.

[2/200] Processing: 000000074256.jpg
[3/200] Processing: 000000022192.jpg
[4/200] Processing: 000000531495.jpg
[5/200] Processing: 000000236426.jpg
[6/200] Processing: 000000161008.jpg
[7/200] Processing: 000000423519.jpg
[8/200] Processing: 000000572303.jpg
[9/200] Processing: 000000161781.jpg
[10/200] Processing: 000000198915.jpg
[11/200] Processing: 000000186938.jpg
[12/200] Processing: 000000102411.jpg
[13/200] Processing: 000000345941.jpg
[14/200] Processing: 000000514797.jpg
[15/200] Processing: 000000226802.jpg
[16/200] Processing: 000000060449.jpg
[17/200] Processing: 000000488075.jpg
[18/200] Processing: 000000419201.jpg
[19/200] Processing: 000000396274.jpg
[20/200] Processing: 000000275198.jpg
[21/200] Processing: 000000259571.jpg
[22/200] Processing: 000000174482.jpg
[23/200] Processing: 000000286507.jpg
[24/200] Processing: 000000314264.jpg
[25/200] Processing: 000000482319.jpg
[26/200] Processing: 000000185250.jpg
[27/200] Processing: 000000059598.jpg
[28/200] Processing: 000000277005.jpg
[29/200] Processing: 000000443844.jpg
[30/200] Processing: 000000458663.jpg
[31/200] Processing: 000000061171.jpg
[32/200] Processing: 000000542856.jpg
[33/200] Processing: 000000410496.jpg
[34/200] Processing: 000000524108.jpg
[35/200] Processing: 000000251537.jpg
[36/200] Processing: 000000368212.jpg
[37/200] Processing: 000000221708.jpg
[38/200] Processing: 000000075456.jpg
[39/200] Processing: 000000225670.jpg
[40/200] Processing: 000000423617.jpg
[41/200] Processing: 000000227478.jpg
[42/200] Processing: 000000429109.jpg
[43/200] Processing: 000000016958.jpg
[44/200] Processing: 000000479912.jpg
[45/200] Processing: 000000575357.jpg
[46/200] Processing: 000000357567.jpg
[47/200] Processing: 000000275791.jpg
[48/200] Processing: 000000452784.jpg
[49/200] Processing: 000000386912.jpg
[50/200] Processing: 000000084431.jpg
Saved to /kaggle/working/rag_quality_vs_recall_200.csv at 50 samples
[51/200] Processing: 000000192607.jpg
[52/200] Processing: 000000326128.jpg
[53/200] Processing: 000000052413.jpg
[54/200] Processing: 000000450399.jpg
[55/200] Processing: 000000277051.jpg
[56/200] Processing: 000000235857.jpg
[57/200] Processing: 000000422670.jpg
[58/200] Processing: 000000396568.jpg
[59/200] Processing: 000000125572.jpg
[60/200] Processing: 000000378116.jpg
[61/200] Processing: 000000128476.jpg
[62/200] Processing: 000000353180.jpg
[63/200] Processing: 000000233370.jpg
[64/200] Processing: 000000205647.jpg
[65/200] Processing: 000000336265.jpg
[66/200] Processing: 000000342295.jpg
[67/200] Processing: 000000163746.jpg
[68/200] Processing: 000000097924.jpg
[69/200] Processing: 000000164115.jpg
[70/200] Processing: 000000375763.jpg
[71/200] Processing: 000000423944.jpg
[72/200] Processing: 000000080273.jpg
[73/200] Processing: 000000356169.jpg
[74/200] Processing: 000000282912.jpg
[75/200] Processing: 000000004395.jpg
[76/200] Processing: 000000194940.jpg
[77/200] Processing: 000000218439.jpg
[78/200] Processing: 000000193162.jpg
[79/200] Processing: 000000279769.jpg
[80/200] Processing: 000000216296.jpg
[81/200] Processing: 000000060886.jpg
[82/200] Processing: 000000044652.jpg
[83/200] Processing: 000000223959.jpg
[84/200] Processing: 000000079188.jpg
[85/200] Processing: 000000018575.jpg
[86/200] Processing: 000000474170.jpg
[87/200] Processing: 000000079034.jpg
[88/200] Processing: 000000336658.jpg
[89/200] Processing: 000000459396.jpg
[90/200] Processing: 000000050326.jpg
[91/200] Processing: 000000199310.jpg
[92/200] Processing: 000000006763.jpg
[93/200] Processing: 000000371552.jpg
[94/200] Processing: 000000263860.jpg
[95/200] Processing: 000000319184.jpg
[96/200] Processing: 000000409867.jpg
[97/200] Processing: 000000180101.jpg
[98/200] Processing: 000000447611.jpg
[99/200] Processing: 000000022755.jpg
[100/200] Processing: 000000544519.jpg
Saved to /kaggle/working/rag_quality_vs_recall_200.csv at 100 samples
[101/200] Processing: 000000071877.jpg
[102/200] Processing: 000000243495.jpg
[103/200] Processing: 000000572555.jpg
[104/200] Processing: 000000133087.jpg
[105/200] Processing: 000000299355.jpg
[106/200] Processing: 000000563648.jpg
[107/200] Processing: 000000242060.jpg
[108/200] Processing: 000000327617.jpg
[109/200] Processing: 000000427034.jpg
[110/200] Processing: 000000257624.jpg
[111/200] Processing: 000000091779.jpg
[112/200] Processing: 000000151000.jpg
[113/200] Processing: 000000022396.jpg
[114/200] Processing: 000000205289.jpg
[115/200] Processing: 000000524742.jpg
[116/200] Processing: 000000283113.jpg
[117/200] Processing: 000000575243.jpg
[118/200] Processing: 000000137294.jpg
[119/200] Processing: 000000227765.jpg
[120/200] Processing: 000000000785.jpg
[121/200] Processing: 000000012120.jpg
[122/200] Processing: 000000147729.jpg
[123/200] Processing: 000000400815.jpg
[124/200] Processing: 000000494913.jpg
[125/200] Processing: 000000136915.jpg
[126/200] Processing: 000000162035.jpg
[127/200] Processing: 000000367569.jpg
[128/200] Processing: 000000507037.jpg
[129/200] Processing: 000000338560.jpg
[130/200] Processing: 000000013004.jpg
[131/200] Processing: 000000140076.jpg
[132/200] Processing: 000000331317.jpg
[133/200] Processing: 000000289222.jpg
[134/200] Processing: 000000026941.jpg
[135/200] Processing: 000000140840.jpg
[136/200] Processing: 000000567886.jpg
[137/200] Processing: 000000216277.jpg
[138/200] Processing: 000000572408.jpg
[139/200] Processing: 000000427160.jpg
[140/200] Processing: 000000569825.jpg
[141/200] Processing: 000000011149.jpg
[142/200] Processing: 000000157124.jpg
[143/200] Processing: 000000210708.jpg
[144/200] Processing: 000000474164.jpg
[145/200] Processing: 000000447522.jpg
[146/200] Processing: 000000303499.jpg
[147/200] Processing: 000000565778.jpg
[148/200] Processing: 000000001675.jpg
[149/200] Processing: 000000177015.jpg
[150/200] Processing: 000000402615.jpg
Saved to /kaggle/working/rag_quality_vs_recall_200.csv at 150 samples
[151/200] Processing: 000000350002.jpg
[152/200] Processing: 000000370208.jpg
[153/200] Processing: 000000447917.jpg
[154/200] Processing: 000000161861.jpg
[155/200] Processing: 000000303713.jpg
[156/200] Processing: 000000466602.jpg
[157/200] Processing: 000000421923.jpg
[158/200] Processing: 000000447789.jpg
[159/200] Processing: 000000076211.jpg
[160/200] Processing: 000000504389.jpg
[161/200] Processing: 000000417085.jpg
[162/200] Processing: 000000192716.jpg
[163/200] Processing: 000000407524.jpg
[164/200] Processing: 000000537812.jpg
[165/200] Processing: 000000152214.jpg
[166/200] Processing: 000000198641.jpg
[167/200] Processing: 000000028452.jpg
[168/200] Processing: 000000222825.jpg
[169/200] Processing: 000000243148.jpg
[170/200] Processing: 000000232489.jpg
[171/200] Processing: 000000439623.jpg
[172/200] Processing: 000000197022.jpg
[173/200] Processing: 000000535578.jpg
[174/200] Processing: 000000183500.jpg
[175/200] Processing: 000000382030.jpg
[176/200] Processing: 000000138241.jpg
[177/200] Processing: 000000421834.jpg
[178/200] Processing: 000000229553.jpg
[179/200] Processing: 000000231097.jpg
[180/200] Processing: 000000104782.jpg
[181/200] Processing: 000000193429.jpg
[182/200] Processing: 000000189806.jpg
[183/200] Processing: 000000122745.jpg
[184/200] Processing: 000000239041.jpg
[185/200] Processing: 000000534041.jpg
[186/200] Processing: 000000512248.jpg
[187/200] Processing: 000000214869.jpg
[188/200] Processing: 000000125472.jpg
[189/200] Processing: 000000236599.jpg
[190/200] Processing: 000000485895.jpg
[191/200] Processing: 000000442323.jpg
[192/200] Processing: 000000128051.jpg
[193/200] Processing: 000000462756.jpg
[194/200] Processing: 000000021503.jpg
[195/200] Processing: 000000228214.jpg
[196/200] Processing: 000000571857.jpg
[197/200] Processing: 000000261888.jpg
[198/200] Processing: 000000156643.jpg
[199/200] Processing: 000000378244.jpg
[200/200] Processing: 000000320425.jpg
Saved to /kaggle/working/rag_quality_vs_recall_200.csv at 200 samples

,image_name,image_path,retrieved_captions,retrieved_scores,retrieved_image_names,hit@1,hit@5,hit@10,raw_rag,answer_rag
0,000000328238.jpg,/kaggle/input/datasets/saptarshim596/val2017-m...,[A guy gets ready to throw a Frisbee during a ...,"[0.38285431265830994, 0.3726266920566559, 0.37...","[000000401244.jpg, 000000409198.jpg, 000000352...",0,0,1,A man in a blue shirt and white hat is prepari...,A man in a blue shirt and white hat is prepari...
1,000000074256.jpg,/kaggle/input/datasets/saptarshim596/val2017-m...,"[Elderly women debark a bus at a station. , A ...","[0.3621743619441986, 0.3537268340587616, 0.331...","[000000507797.jpg, 000000517069.jpg, 000000052...",0,0,1,Two women standing next to each other in a tra...,Two women standing next to each other in a tra...
2,000000022192.jpg,/kaggle/input/datasets/saptarshim596/val2017-m...,"[A dog sitting on a bed covered with clothing,...","[0.366780549287796, 0.35598838329315186, 0.350...","[000000022192.jpg, 000000022192.jpg, 000000022...",1,1,1,"A dog sitting on a bed covered with clothing, ...","A dog sitting on a bed covered with clothing, ..."
3,000000531495.jpg,/kaggle/input/datasets/saptarshim596/val2017-m...,[Looking out over a bay with many tourist boat...,"[0.294355183839798, 0.29095879197120667, 0.282...","[000000050006.jpg, 000000490470.jpg, 000000328...",0,1,1,A harbor with several boats docked and buildin...,A harbor with several boats docked and buildin...
4,000000236426.jpg,/kaggle/input/datasets/saptarshim596/val2017-m...,[A white-clad tennis player hurls a ball upwar...,"[0.32634979486465454, 0.3248714506626129, 0.32...","[000000269121.jpg, 000000261097.jpg, 000000080...",0,0,0,A male tennis player in white shorts is playin...,A male tennis player in white shorts is playin...

### Analysis of responses

In [23]:
from collections import defaultdict

gt_map = defaultdict(list)
for _, row in df.iterrows():
    gt_map[str(row["image_name"]).strip()].append(str(row["comment"]).strip())

df_rag_recall["references"] = df_rag_recall["image_name"].map(gt_map)
df_eval = df_rag_recall[df_rag_recall["references"].notna()].copy()

In [24]:
import numpy as np
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

smooth = SmoothingFunction().method1
rouge = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

def bleu_against_refs(pred, refs):
    pred_tokens = pred.split()
    ref_tokens = [r.split() for r in refs]
    return sentence_bleu(ref_tokens, pred_tokens, smoothing_function=smooth)

def best_rouge_against_refs(pred, refs):
    best = {"rouge1": 0.0, "rouge2": 0.0, "rougeL": 0.0}
    for ref in refs:
        scores = rouge.score(ref, pred)
        for k in best:
            best[k] = max(best[k], scores[k].fmeasure)
    return best

In [25]:
rag_bleu = []
rag_r1, rag_r2, rag_rL = [], [], []

for _, row in df_eval.iterrows():
    refs = row["references"]
    pred = str(row["answer_rag"]).strip()

    rag_bleu.append(bleu_against_refs(pred, refs))

    rs = best_rouge_against_refs(pred, refs)
    rag_r1.append(rs["rouge1"])
    rag_r2.append(rs["rouge2"])
    rag_rL.append(rs["rougeL"])

df_eval["bleu_rag"] = rag_bleu
df_eval["rouge1_rag"] = rag_r1
df_eval["rouge2_rag"] = rag_r2
df_eval["rougeL_rag"] = rag_rL

In [26]:
@torch.no_grad()
def compute_clipscore_single(img_path, caption):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess(img).unsqueeze(0).to(device)
    img_feat = clip_model.encode_image(img_in)
    img_feat = img_feat / img_feat.norm(dim=-1, keepdim=True)

    tokens = open_clip.tokenize([caption]).to(device)
    txt_feat = clip_model.encode_text(tokens)
    txt_feat = txt_feat / txt_feat.norm(dim=-1, keepdim=True)

    return (img_feat * txt_feat).sum(dim=-1).item()

In [27]:
clip_scores = []
for _, row in df_eval.iterrows():
    clip_scores.append(
        compute_clipscore_single(row["image_path"], str(row["answer_rag"]).strip())
    )

df_eval["clipscore_rag"] = clip_scores

In [28]:
df_eval.to_csv('/kaggle/working/df_eval_mscoco_responses.csv')

In [29]:
def summarize_by_hit(df_eval, hit_col):
    rows = []

    for val in [0, 1]:
        sub = df_eval[df_eval[hit_col] == val]

        if len(sub) == 0:
            continue

        rows.append({
            "Group": f"{hit_col}={val}",
            "Count": len(sub),

            "BLEU": f"{sub['bleu_rag'].mean():.4f} ± {sub['bleu_rag'].std():.4f}",
            "ROUGE-1": f"{sub['rouge1_rag'].mean():.4f} ± {sub['rouge1_rag'].std():.4f}",
            "ROUGE-2": f"{sub['rouge2_rag'].mean():.4f} ± {sub['rouge2_rag'].std():.4f}",
            "ROUGE-L": f"{sub['rougeL_rag'].mean():.4f} ± {sub['rougeL_rag'].std():.4f}",
            "CLIPScore": f"{sub['clipscore_rag'].mean():.4f} ± {sub['clipscore_rag'].std():.4f}"
        })

    return pd.DataFrame(rows)

In [30]:
summary_hit1 = summarize_by_hit(df_eval, "hit@1")
summary_hit5 = summarize_by_hit(df_eval, "hit@5")
summary_hit10 = summarize_by_hit(df_eval, "hit@10")

print("=== Quality vs hit@1 ===")
print(summary_hit1)

print("\n=== Quality vs hit@5 ===")
print(summary_hit5)

print("\n=== Quality vs hit@10 ===")
print(summary_hit10)

=== Quality vs hit@1 ===
     Group  Count             BLEU          ROUGE-1          ROUGE-2  \
0  hit@1=0     95  0.3217 ± 0.3235  0.6361 ± 0.2140  0.4152 ± 0.2994
1  hit@1=1    105  0.7010 ± 0.3425  0.8430 ± 0.1927  0.7358 ± 0.2999

           ROUGE-L        CLIPScore
0  0.6001 ± 0.2291  0.3274 ± 0.0341
1  0.8272 ± 0.2127  0.3452 ± 0.0448

=== Quality vs hit@5 ===
     Group  Count             BLEU          ROUGE-1          ROUGE-2  \
0  hit@5=0     39  0.2227 ± 0.2369  0.5805 ± 0.1852  0.3202 ± 0.2183
1  hit@5=1    161  0.5930 ± 0.3773  0.7845 ± 0.2193  0.6473 ± 0.3329

           ROUGE-L        CLIPScore
0  0.5353 ± 0.1860  0.3174 ± 0.0306
1  0.7639 ± 0.2406  0.3414 ± 0.0418

=== Quality vs hit@10 ===
      Group  Count             BLEU          ROUGE-1          ROUGE-2  \
0  hit@10=0     20  0.1562 ± 0.1577  0.5514 ± 0.1788  0.2638 ± 0.1593
1  hit@10=1    180  0.5613 ± 0.3796  0.7662 ± 0.2225  0.6190 ± 0.3355

           ROUGE-L        CLIPScore
0  0.5053 ± 0.1637  0.3218 ± 0.0205
1  0.7431 ± 0.2444  0.3384 ± 0.0423

In [31]:
overall_rows = []

for hit_col in ["hit@1", "hit@5", "hit@10"]:
    for val in [0, 1]:
        sub = df_eval[df_eval[hit_col] == val]
        if len(sub) == 0:
            continue

        overall_rows.append({
            "Condition": f"{hit_col}={val}",
            "Count": len(sub),

            "BLEU": f"{sub['bleu_rag'].mean():.4f} ± {sub['bleu_rag'].std():.4f}",
            "ROUGE-1": f"{sub['rouge1_rag'].mean():.4f} ± {sub['rouge1_rag'].std():.4f}",
            "ROUGE-2": f"{sub['rouge2_rag'].mean():.4f} ± {sub['rouge2_rag'].std():.4f}",
            "ROUGE-L": f"{sub['rougeL_rag'].mean():.4f} ± {sub['rougeL_rag'].std():.4f}",
            "CLIPScore": f"{sub['clipscore_rag'].mean():.4f} ± {sub['clipscore_rag'].std():.4f}"
        })

quality_vs_recall_df = pd.DataFrame(overall_rows)
quality_vs_recall_df

,Condition,Count,BLEU,ROUGE-1,ROUGE-2,ROUGE-L,CLIPScore
0,hit@1=0,95,0.3217 ± 0.3235,0.6361 ± 0.2140,0.4152 ± 0.2994,0.6001 ± 0.2291,0.3274 ± 0.0341
1,hit@1=1,105,0.7010 ± 0.3425,0.8430 ± 0.1927,0.7358 ± 0.2999,0.8272 ± 0.2127,0.3452 ± 0.0448
2,hit@5=0,39,0.2227 ± 0.2369,0.5805 ± 0.1852,0.3202 ± 0.2183,0.5353 ± 0.1860,0.3174 ± 0.0306
3,hit@5=1,161,0.5930 ± 0.3773,0.7845 ± 0.2193,0.6473 ± 0.3329,0.7639 ± 0.2406,0.3414 ± 0.0418
4,hit@10=0,20,0.1562 ± 0.1577,0.5514 ± 0.1788,0.2638 ± 0.1593,0.5053 ± 0.1637,0.3218 ± 0.0205
5,hit@10=1,180,0.5613 ± 0.3796,0.7662 ± 0.2225,0.6190 ± 0.3355,0.7431 ± 0.2444,0.3384 ± 0.0423

In [32]:
quality_vs_recall_df.to_csv('/kaggle/working/quality_recall_responses_mscoco.csv')

In [33]:
def compute_improvement(df_eval, hit_col):
    sub0 = df_eval[df_eval[hit_col] == 0]
    sub1 = df_eval[df_eval[hit_col] == 1]

    if len(sub0) == 0 or len(sub1) == 0:
        return None

    print(f"\n=== Improvement for {hit_col} ===")
    print(f"Count (0): {len(sub0)}, Count (1): {len(sub1)}")

    for metric in ["bleu_rag", "rouge1_rag", "rouge2_rag", "rougeL_rag", "clipscore_rag"]:
        gain = sub1[metric].mean() - sub0[metric].mean()
        print(f"{metric}: +{gain:.4f}")

In [34]:
for hit_col in ["hit@1", "hit@5", "hit@10"]:
    compute_improvement(df_eval, hit_col)

=== Improvement for hit@1 ===
Count (0): 95, Count (1): 105
bleu_rag: +0.3793
rouge1_rag: +0.2069
rouge2_rag: +0.3206
rougeL_rag: +0.2271
clipscore_rag: +0.0178

=== Improvement for hit@5 ===
Count (0): 39, Count (1): 161
bleu_rag: +0.3703
rouge1_rag: +0.2040
rouge2_rag: +0.3271
rougeL_rag: +0.2286
clipscore_rag: +0.0240

=== Improvement for hit@10 ===
Count (0): 20, Count (1): 180
bleu_rag: +0.4051
rouge1_rag: +0.2148
rouge2_rag: +0.3553
rougeL_rag: +0.2378
clipscore_rag: +0.0167

### Conducting significance test to see whether the result is significant

In [35]:
!pip install scipy

Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from scipy) (2.0.2)

In [36]:
from scipy.stats import ttest_ind

def significance_test(df_eval, hit_col):
    sub0 = df_eval[df_eval[hit_col] == 0]
    sub1 = df_eval[df_eval[hit_col] == 1]

    if len(sub0) == 0 or len(sub1) == 0:
        return None

    print(f"\n=== Significance test for {hit_col} ===")

    for metric in ["bleu_rag", "rouge1_rag", "rouge2_rag", "rougeL_rag", "clipscore_rag"]:
        stat, pval = ttest_ind(sub1[metric], sub0[metric], equal_var=False)

        print(f"{metric}: p-value = {pval:.6f}")

In [37]:
for hit_col in ["hit@1", "hit@5", "hit@10"]:
    significance_test(df_eval, hit_col)

=== Significance test for hit@1 ===
bleu_rag: p-value = 0.000000
rouge1_rag: p-value = 0.000000
rouge2_rag: p-value = 0.000000
rougeL_rag: p-value = 0.000000
clipscore_rag: p-value = 0.001710

=== Significance test for hit@5 ===
bleu_rag: p-value = 0.000000
rouge1_rag: p-value = 0.000000
rouge2_rag: p-value = 0.000000
rougeL_rag: p-value = 0.000000
clipscore_rag: p-value = 0.000116

=== Significance test for hit@10 ===
bleu_rag: p-value = 0.000000
rouge1_rag: p-value = 0.000037
rouge2_rag: p-value = 0.000000
rougeL_rag: p-value = 0.000003
clipscore_rag: p-value = 0.004766