In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O

In [2]:
!pip uninstall -y transformers accelerate -q
!pip install -q transformers==4.43.0 accelerate==0.30.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 73.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 kB 21.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 35.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 104.1 MB/s eta 0:00:00

### Importing the MSCOCO validation dataset

In [3]:
import os

BASE = "/kaggle/input/datasets/saptarshim596/val2017-ms-coco/val2017"
IMG_DIR = os.path.join(BASE, "val2017")
CAPTION_FILE = "/kaggle/input/datasets/saptarshim596/val2017-ms-coco/coco_captions.csv"

print("Image folder:", IMG_DIR)
print("Caption file:", CAPTION_FILE)

Image folder: /kaggle/input/datasets/saptarshim596/val2017-ms-coco/val2017/val2017
Caption file: /kaggle/input/datasets/saptarshim596/val2017-ms-coco/coco_captions.csv

In [4]:
print("Number of images:", len(os.listdir(IMG_DIR)))
print(os.listdir(IMG_DIR)[:10])

Number of images: 5000
['000000011197.jpg', '000000219485.jpg', '000000151000.jpg', '000000371677.jpg', '000000038825.jpg', '000000384527.jpg', '000000122969.jpg', '000000028809.jpg', '000000053505.jpg', '000000384513.jpg']

In [5]:
import pandas as pd

df = pd.read_csv(CAPTION_FILE, sep=',')
df.head()

         image_name                                            comment
0  000000179765.jpg  A black Honda motorcycle parked in front of a ...
1  000000179765.jpg      A Honda motorcycle parked in a grass driveway
2  000000190236.jpg  An office cubicle with four different types of...
3  000000331352.jpg          A small closed toilet in a cramped space.
4  000000517069.jpg     Two women waiting at a bench next to a street.

In [6]:
df.columns = df.columns.str.strip()

In [7]:
!pip -q install open_clip_torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 24.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 3.6 MB/s eta 0:00:00

In [8]:
import torch
import open_clip
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

clip_model, _, preprocess = open_clip.create_model_and_transforms(
    "ViT-B-32",
    pretrained="laion2b_s34b_b79k"
)
tokenizer = open_clip.get_tokenizer("ViT-B-32")

clip_model = clip_model.to(device).eval()
print("Device:", device)

open_clip_model.safetensors:   0%|          | 0.00/605M [00:00<?, ?B/s]

Device: cuda

In [9]:
CAPTION_N = 200000

cap_df = df.sample(n=min(CAPTION_N, len(df)), random_state=42).reset_index(drop=True)
captions = cap_df["comment"].astype(str).tolist()

print("Captions in pool:", len(captions))

Captions in pool: 25014

In [10]:
@torch.no_grad()
def encode_texts(text_list, batch_size=256):
    embs = []
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        tokens = tokenizer(batch).to(device)
        feat = clip_model.encode_text(tokens)
        feat = feat / feat.norm(dim=-1, keepdim=True)
        embs.append(feat.cpu())
    return torch.cat(embs, dim=0)

In [11]:
from PIL import Image
import matplotlib.pyplot as plt
import os, random

@torch.no_grad()
def encode_image(img_path):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess(img).unsqueeze(0).to(device)
    feat = clip_model.encode_image(img_in)
    feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.cpu(), img

In [12]:
import transformers, accelerate, torch
print(transformers.__version__)
print(accelerate.__version__)
print(torch.__version__)

4.43.0
0.30.0
2.9.0+cu126

### Phi-3.5-vision-instruct  model

In [13]:
import os
import torch
from transformers import AutoConfig, AutoProcessor, AutoModelForCausalLM
from huggingface_hub import login

os.environ["HF_HOME"] = "/kaggle/working/hf_cache"
os.environ["TRANSFORMERS_CACHE"] = "/kaggle/working/hf_cache"

# Login
login(token="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")

VLM_NAME = "microsoft/Phi-3.5-vision-instruct"

config = AutoConfig.from_pretrained(
    VLM_NAME,
    trust_remote_code=True
)
config._attn_implementation = "eager"

processor = AutoProcessor.from_pretrained(
    VLM_NAME,
    trust_remote_code=True  
)

phi_model = AutoModelForCausalLM.from_pretrained(
    VLM_NAME,
    config=config,
    trust_remote_code=True,
    device_map="auto",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
).eval()

2026-04-05 12:21:14.755646: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1775391674.988981      24 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1775391675.052670      24 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1775391675.559920      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775391675.559947      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775391675.559950      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775391675.559953      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

config.json: 0.00B [00:00, ?B/s]

configuration_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- configuration_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

processor_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

processing_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- processing_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
/usr/local/lib/python3.12/dist-packages/transformers/models/auto/image_processing_auto.py:513: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(

preprocessor_config.json:   0%|          | 0.00/442 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/670 [00:00<?, ?B/s]

modeling_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- modeling_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.35G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/136 [00:00<?, ?B/s]

## Llava-1.5-7b model

In [14]:
import os
import torch
from transformers import LlavaForConditionalGeneration, AutoProcessor
from huggingface_hub import login

os.environ["HF_HOME"] = "/kaggle/working/hf_cache"
os.environ["TRANSFORMERS_CACHE"] = "/kaggle/working/hf_cache"

login(token="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")

LLAVA_NAME = "llava-hf/llava-1.5-7b-hf"
LLAVA_REVISION = "a272c74"   

llava_processor = AutoProcessor.from_pretrained(
    LLAVA_NAME,
    revision=LLAVA_REVISION
)

llava_model = LlavaForConditionalGeneration.from_pretrained(
    LLAVA_NAME,
    revision=LLAVA_REVISION,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto",
    low_cpu_mem_usage=True
).eval()

preprocessor_config.json:   0%|          | 0.00/505 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/41.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/552 [00:00<?, ?B/s]

chat_template.json:   0%|          | 0.00/700 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/950 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.96G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.18G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/141 [00:00<?, ?B/s]

### Analysis of responses for the 2 LLMs

In [15]:
CAPTION_N = 200000

cap_df = df.sample(n=min(CAPTION_N, len(df)), random_state=42).reset_index(drop=True)

captions = cap_df["comment"].astype(str).tolist()

print("Captions in pool:", len(captions))

Captions in pool: 25014

In [16]:
@torch.no_grad()
def encode_captions(text_list, batch_size=256):
    embs = []

    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]

        tokens = open_clip.tokenize(batch).to(device)

        feat = clip_model.encode_text(tokens)

        # Normalize (important for cosine similarity)
        feat = feat / feat.norm(dim=-1, keepdim=True)

        embs.append(feat.cpu())

        if i % (batch_size * 10) == 0:
            print(f"Processed {i}/{len(text_list)} captions")

    return torch.cat(embs, dim=0)

In [17]:
caption_embs = encode_captions(captions, batch_size=256)

print("Caption embeddings:", caption_embs.shape)

Processed 0/25014 captions
Processed 2560/25014 captions
Processed 5120/25014 captions
Processed 7680/25014 captions
Processed 10240/25014 captions
Processed 12800/25014 captions
Processed 15360/25014 captions
Processed 17920/25014 captions
Processed 20480/25014 captions
Processed 23040/25014 captions
Caption embeddings: torch.Size([25014, 512])

In [18]:
torch.save(caption_embs, "/kaggle/working/caption_embs_all.pt")

In [19]:
caption_embs = torch.load("/kaggle/working/caption_embs_all.pt")

In [20]:
import os
import random
import re
import torch
import pandas as pd
from PIL import Image


def clean_answer(text):
    text = text.strip()

    stop_markers = [
        "# User", "# Assistant", "# Input", "# Output", "##",
        "<|user|>", "<|assistant|>", "<|end|>"
    ]

    for marker in stop_markers:
        if marker in text:
            text = text.split(marker)[0].strip()

    sentences = re.split(r'(?<=[.!?])\s+', text)
    return " ".join(sentences[:1]).strip()


@torch.no_grad()
def encode_image(img_path):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess(img).unsqueeze(0).to(device)
    feat = clip_model.encode_image(img_in)
    feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.cpu(), img


def get_random_image_embeddings(img_dir, num_samples=10, seed=42):
    random.seed(seed)

    all_images = [
        os.path.join(img_dir, f)
        for f in os.listdir(img_dir)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    if not all_images:
        raise ValueError(f"No image files found in: {img_dir}")

    sampled_images = random.sample(all_images, min(num_samples, len(all_images)))

    embeddings = []
    image_objects = []
    image_paths = []

    for img_path in sampled_images:
        feat, img = encode_image(img_path)
        embeddings.append(feat)
        image_objects.append(img)
        image_paths.append(img_path)

    embeddings = torch.cat(embeddings, dim=0)   # (N, D)
    return embeddings, image_objects, image_paths

In [21]:
def retrieve_topk_captions_for_image(image_emb, caption_embs, captions, caption_image_names, k=10):
    """
    image_emb: tensor of shape (D,) or (1, D)
    caption_embs: tensor of shape (M, D)
    captions: list[str]
    caption_image_names: list[str]
    """
    if image_emb.dim() == 1:
        image_emb = image_emb.unsqueeze(0)

    sims = image_emb @ caption_embs.T
    top_scores, top_idx = torch.topk(sims, k=min(k, len(captions)), dim=1)

    results = []
    for score, idx in zip(top_scores[0].tolist(), top_idx[0].tolist()):
        results.append({
            "score": score,
            "caption": captions[idx],
            "caption_image_name": caption_image_names[idx]
        })

    return results

In [22]:
@torch.no_grad()
def generate_with_rag_phi(img_path, retrieved_caps, phi_model, processor, max_new_tokens=25):
    image = Image.open(img_path).convert("RGB")

    context_block = "\n".join([f"- {cap}" for _, cap in retrieved_caps])

    prompt = f"""<|user|>
<|image_1|>
Describe this image in one sentence.

Helpful retrieved captions:
{context_block}

Only answer with the description sentence.
<|end|>
<|assistant|>
"""

    inputs = processor(
        text=prompt,
        images=image,
        return_tensors="pt"
    )

    for k, v in inputs.items():
        if hasattr(v, "to"):
            inputs[k] = v.to(phi_model.device)

    outputs = phi_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        use_cache=True,   # can keep True for speed
        eos_token_id=processor.tokenizer.eos_token_id,
        pad_token_id=processor.tokenizer.eos_token_id
    )

    generated_ids = outputs[:, inputs["input_ids"].shape[1]:]

    raw_answer = processor.tokenizer.decode(
        generated_ids[0],
        skip_special_tokens=True
    ).strip()

    return raw_answer, clean_answer(raw_answer)

In [23]:
@torch.no_grad()
def generate_with_rag_llava(img_path, retrieved_caps, llava_model, llava_processor, max_new_tokens=25):
    image = Image.open(img_path).convert("RGB")

    context_block = "\n".join([f"- {cap}" for _, cap in retrieved_caps])

    prompt = f"""USER: <image>
Describe this image in one sentence.

Helpful retrieved captions:
{context_block}

Only answer with the description sentence.
ASSISTANT:"""

    inputs = llava_processor(
        text=prompt,
        images=image,
        return_tensors="pt"
    )

    for k, v in inputs.items():
        if hasattr(v, "to"):
            inputs[k] = v.to(llava_model.device)

    outputs = llava_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        use_cache=True
    )

    generated_ids = outputs[:, inputs["input_ids"].shape[1]:]

    raw_answer = llava_processor.tokenizer.decode(
        generated_ids[0],
        skip_special_tokens=True
    ).strip()

    return raw_answer, clean_answer(raw_answer)

### Getting responses from the 2 LLMs for the same image

In [24]:
import os
import pandas as pd

def run_phi_vs_llava_rag_pipeline(
    img_dir,
    caption_embs,
    captions,
    caption_image_names,
    phi_model,
    phi_processor,
    llava_model,
    llava_processor,
    num_samples=100,
    seed=42,
    k=5,
    save_every=25,
    save_path="/kaggle/working/phi_vs_llava_rag.csv"
):
    sampled_img_embs, _, sampled_img_paths = get_random_image_embeddings(
        img_dir,
        num_samples=num_samples,
        seed=seed
    )

    outputs = []

    for i, img_path in enumerate(sampled_img_paths):
        image_name = os.path.basename(img_path)
        print(f"[{i+1}/{len(sampled_img_paths)}] Processing: {image_name}")

        image_emb = sampled_img_embs[i]

        retrieved = retrieve_topk_captions_for_image(
            image_emb=image_emb,
            caption_embs=caption_embs,
            captions=captions,
            caption_image_names=caption_image_names,
            k=k
        )

        retrieved_caps = [(x["score"], x["caption"]) for x in retrieved]
        retrieved_names = [x["caption_image_name"] for x in retrieved]

        # Optional: keep retrieval hits for reference
        hit1 = int(any(name == image_name for name in retrieved_names[:1]))
        hit5 = int(any(name == image_name for name in retrieved_names[:5]))
        hit10 = int(any(name == image_name for name in retrieved_names[:10]))

        # Phi
        raw_phi, ans_phi = generate_with_rag_phi(
            img_path=img_path,
            retrieved_caps=retrieved_caps,
            phi_model=phi_model,
            processor=phi_processor
        )

        # LLaVA
        raw_llava, ans_llava = generate_with_rag_llava(
            img_path=img_path,
            retrieved_caps=retrieved_caps,
            llava_model=llava_model,
            llava_processor=llava_processor
        )

        outputs.append({
            "image_name": image_name,
            "image_path": img_path,

            "retrieved_captions": [x["caption"] for x in retrieved],
            "retrieved_scores": [x["score"] for x in retrieved],
            "retrieved_image_names": retrieved_names,

            "hit@1": hit1,
            "hit@5": hit5,
            "hit@10": hit10,

            "raw_phi": raw_phi,
            "answer_phi": ans_phi,

            "raw_llava": raw_llava,
            "answer_llava": ans_llava
        })

        if (i + 1) % save_every == 0 or (i + 1) == len(sampled_img_paths):
            pd.DataFrame(outputs).to_csv(save_path, index=False)
            print(f"Saved to {save_path} at {i+1} samples")

    return pd.DataFrame(outputs)

In [25]:
caption_image_names = cap_df["image_name"].astype(str).tolist()

In [26]:
df_phi_llava = run_phi_vs_llava_rag_pipeline(
    img_dir=IMG_DIR,
    caption_embs=caption_embs,
    captions=captions,
    caption_image_names=caption_image_names,
    phi_model=phi_model,
    phi_processor=processor,
    llava_model=llava_model,
    llava_processor=llava_processor,
    num_samples=500,
    seed=123,
    k=5,
    save_every=20,
    save_path="/kaggle/working/phi_vs_llava_rag_500_mscoco.csv"
)

df_phi_llava.head()

The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.

[1/500] Processing: 000000328238.jpg

WARNING:transformers_modules.microsoft.Phi-3.5-vision-instruct.12b77fb40b63a2c73c68243d3f767aab688a1b2a.modeling_phi3_v:You are not running the flash-attention implementation, expect numerical differences.
We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)

[2/500] Processing: 000000074256.jpg
[3/500] Processing: 000000022192.jpg
[4/500] Processing: 000000531495.jpg
[5/500] Processing: 000000236426.jpg
[6/500] Processing: 000000161008.jpg
[7/500] Processing: 000000423519.jpg
[8/500] Processing: 000000572303.jpg
[9/500] Processing: 000000161781.jpg
[10/500] Processing: 000000198915.jpg
[11/500] Processing: 000000186938.jpg
[12/500] Processing: 000000102411.jpg
[13/500] Processing: 000000345941.jpg
[14/500] Processing: 000000514797.jpg
[15/500] Processing: 000000226802.jpg
[16/500] Processing: 000000060449.jpg
[17/500] Processing: 000000488075.jpg
[18/500] Processing: 000000419201.jpg
[19/500] Processing: 000000396274.jpg
[20/500] Processing: 000000275198.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 20 samples
[21/500] Processing: 000000259571.jpg
[22/500] Processing: 000000174482.jpg
[23/500] Processing: 000000286507.jpg
[24/500] Processing: 000000314264.jpg
[25/500] Processing: 000000482319.jpg
[26/500] Processing: 000000185250.jpg
[27/500] Processing: 000000059598.jpg
[28/500] Processing: 000000277005.jpg
[29/500] Processing: 000000443844.jpg
[30/500] Processing: 000000458663.jpg
[31/500] Processing: 000000061171.jpg
[32/500] Processing: 000000542856.jpg
[33/500] Processing: 000000410496.jpg
[34/500] Processing: 000000524108.jpg
[35/500] Processing: 000000251537.jpg
[36/500] Processing: 000000368212.jpg
[37/500] Processing: 000000221708.jpg
[38/500] Processing: 000000075456.jpg
[39/500] Processing: 000000225670.jpg
[40/500] Processing: 000000423617.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 40 samples
[41/500] Processing: 000000227478.jpg
[42/500] Processing: 000000429109.jpg
[43/500] Processing: 000000016958.jpg
[44/500] Processing: 000000479912.jpg
[45/500] Processing: 000000575357.jpg
[46/500] Processing: 000000357567.jpg
[47/500] Processing: 000000275791.jpg
[48/500] Processing: 000000452784.jpg
[49/500] Processing: 000000386912.jpg
[50/500] Processing: 000000084431.jpg
[51/500] Processing: 000000192607.jpg
[52/500] Processing: 000000326128.jpg
[53/500] Processing: 000000052413.jpg
[54/500] Processing: 000000450399.jpg
[55/500] Processing: 000000277051.jpg
[56/500] Processing: 000000235857.jpg
[57/500] Processing: 000000422670.jpg
[58/500] Processing: 000000396568.jpg
[59/500] Processing: 000000125572.jpg
[60/500] Processing: 000000378116.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 60 samples
[61/500] Processing: 000000128476.jpg
[62/500] Processing: 000000353180.jpg
[63/500] Processing: 000000233370.jpg
[64/500] Processing: 000000205647.jpg
[65/500] Processing: 000000336265.jpg
[66/500] Processing: 000000342295.jpg
[67/500] Processing: 000000163746.jpg
[68/500] Processing: 000000097924.jpg
[69/500] Processing: 000000164115.jpg
[70/500] Processing: 000000375763.jpg
[71/500] Processing: 000000423944.jpg
[72/500] Processing: 000000080273.jpg
[73/500] Processing: 000000356169.jpg
[74/500] Processing: 000000282912.jpg
[75/500] Processing: 000000004395.jpg
[76/500] Processing: 000000194940.jpg
[77/500] Processing: 000000218439.jpg
[78/500] Processing: 000000193162.jpg
[79/500] Processing: 000000279769.jpg
[80/500] Processing: 000000216296.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 80 samples
[81/500] Processing: 000000060886.jpg
[82/500] Processing: 000000044652.jpg
[83/500] Processing: 000000223959.jpg
[84/500] Processing: 000000079188.jpg
[85/500] Processing: 000000018575.jpg
[86/500] Processing: 000000474170.jpg
[87/500] Processing: 000000079034.jpg
[88/500] Processing: 000000336658.jpg
[89/500] Processing: 000000459396.jpg
[90/500] Processing: 000000050326.jpg
[91/500] Processing: 000000199310.jpg
[92/500] Processing: 000000006763.jpg
[93/500] Processing: 000000371552.jpg
[94/500] Processing: 000000263860.jpg
[95/500] Processing: 000000319184.jpg
[96/500] Processing: 000000409867.jpg
[97/500] Processing: 000000180101.jpg
[98/500] Processing: 000000447611.jpg
[99/500] Processing: 000000022755.jpg
[100/500] Processing: 000000544519.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 100 samples
[101/500] Processing: 000000071877.jpg
[102/500] Processing: 000000243495.jpg
[103/500] Processing: 000000572555.jpg
[104/500] Processing: 000000133087.jpg
[105/500] Processing: 000000299355.jpg
[106/500] Processing: 000000563648.jpg
[107/500] Processing: 000000242060.jpg
[108/500] Processing: 000000327617.jpg
[109/500] Processing: 000000427034.jpg
[110/500] Processing: 000000257624.jpg
[111/500] Processing: 000000091779.jpg
[112/500] Processing: 000000151000.jpg
[113/500] Processing: 000000022396.jpg
[114/500] Processing: 000000205289.jpg
[115/500] Processing: 000000524742.jpg
[116/500] Processing: 000000283113.jpg
[117/500] Processing: 000000575243.jpg
[118/500] Processing: 000000137294.jpg
[119/500] Processing: 000000227765.jpg
[120/500] Processing: 000000000785.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 120 samples
[121/500] Processing: 000000012120.jpg
[122/500] Processing: 000000147729.jpg
[123/500] Processing: 000000400815.jpg
[124/500] Processing: 000000494913.jpg
[125/500] Processing: 000000136915.jpg
[126/500] Processing: 000000162035.jpg
[127/500] Processing: 000000367569.jpg
[128/500] Processing: 000000507037.jpg
[129/500] Processing: 000000338560.jpg
[130/500] Processing: 000000013004.jpg
[131/500] Processing: 000000140076.jpg
[132/500] Processing: 000000331317.jpg
[133/500] Processing: 000000289222.jpg
[134/500] Processing: 000000026941.jpg
[135/500] Processing: 000000140840.jpg
[136/500] Processing: 000000567886.jpg
[137/500] Processing: 000000216277.jpg
[138/500] Processing: 000000572408.jpg
[139/500] Processing: 000000427160.jpg
[140/500] Processing: 000000569825.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 140 samples
[141/500] Processing: 000000011149.jpg
[142/500] Processing: 000000157124.jpg
[143/500] Processing: 000000210708.jpg
[144/500] Processing: 000000474164.jpg
[145/500] Processing: 000000447522.jpg
[146/500] Processing: 000000303499.jpg
[147/500] Processing: 000000565778.jpg
[148/500] Processing: 000000001675.jpg
[149/500] Processing: 000000177015.jpg
[150/500] Processing: 000000402615.jpg
[151/500] Processing: 000000350002.jpg
[152/500] Processing: 000000370208.jpg
[153/500] Processing: 000000447917.jpg
[154/500] Processing: 000000161861.jpg
[155/500] Processing: 000000303713.jpg
[156/500] Processing: 000000466602.jpg
[157/500] Processing: 000000421923.jpg
[158/500] Processing: 000000447789.jpg
[159/500] Processing: 000000076211.jpg
[160/500] Processing: 000000504389.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 160 samples
[161/500] Processing: 000000417085.jpg
[162/500] Processing: 000000192716.jpg
[163/500] Processing: 000000407524.jpg
[164/500] Processing: 000000537812.jpg
[165/500] Processing: 000000152214.jpg
[166/500] Processing: 000000198641.jpg
[167/500] Processing: 000000028452.jpg
[168/500] Processing: 000000222825.jpg
[169/500] Processing: 000000243148.jpg
[170/500] Processing: 000000232489.jpg
[171/500] Processing: 000000439623.jpg
[172/500] Processing: 000000197022.jpg
[173/500] Processing: 000000535578.jpg
[174/500] Processing: 000000183500.jpg
[175/500] Processing: 000000382030.jpg
[176/500] Processing: 000000138241.jpg
[177/500] Processing: 000000421834.jpg
[178/500] Processing: 000000229553.jpg
[179/500] Processing: 000000231097.jpg
[180/500] Processing: 000000104782.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 180 samples
[181/500] Processing: 000000193429.jpg
[182/500] Processing: 000000189806.jpg
[183/500] Processing: 000000122745.jpg
[184/500] Processing: 000000239041.jpg
[185/500] Processing: 000000534041.jpg
[186/500] Processing: 000000512248.jpg
[187/500] Processing: 000000214869.jpg
[188/500] Processing: 000000125472.jpg
[189/500] Processing: 000000236599.jpg
[190/500] Processing: 000000485895.jpg
[191/500] Processing: 000000442323.jpg
[192/500] Processing: 000000128051.jpg
[193/500] Processing: 000000462756.jpg
[194/500] Processing: 000000021503.jpg
[195/500] Processing: 000000228214.jpg
[196/500] Processing: 000000571857.jpg
[197/500] Processing: 000000261888.jpg
[198/500] Processing: 000000156643.jpg
[199/500] Processing: 000000378244.jpg
[200/500] Processing: 000000320425.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 200 samples
[201/500] Processing: 000000429598.jpg
[202/500] Processing: 000000435205.jpg
[203/500] Processing: 000000551439.jpg
[204/500] Processing: 000000244592.jpg
[205/500] Processing: 000000322211.jpg
[206/500] Processing: 000000363840.jpg
[207/500] Processing: 000000069138.jpg
[208/500] Processing: 000000509008.jpg
[209/500] Processing: 000000399296.jpg
[210/500] Processing: 000000278848.jpg
[211/500] Processing: 000000289586.jpg
[212/500] Processing: 000000260925.jpg
[213/500] Processing: 000000258911.jpg
[214/500] Processing: 000000098716.jpg
[215/500] Processing: 000000311789.jpg
[216/500] Processing: 000000546219.jpg
[217/500] Processing: 000000104572.jpg
[218/500] Processing: 000000570688.jpg
[219/500] Processing: 000000138115.jpg
[220/500] Processing: 000000446005.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 220 samples
[221/500] Processing: 000000396903.jpg
[222/500] Processing: 000000031817.jpg
[223/500] Processing: 000000080022.jpg
[224/500] Processing: 000000149622.jpg
[225/500] Processing: 000000209142.jpg
[226/500] Processing: 000000134322.jpg
[227/500] Processing: 000000007888.jpg
[228/500] Processing: 000000097337.jpg
[229/500] Processing: 000000332351.jpg
[230/500] Processing: 000000398438.jpg
[231/500] Processing: 000000194506.jpg
[232/500] Processing: 000000273493.jpg
[233/500] Processing: 000000376206.jpg
[234/500] Processing: 000000211069.jpg
[235/500] Processing: 000000002532.jpg
[236/500] Processing: 000000152771.jpg
[237/500] Processing: 000000213605.jpg
[238/500] Processing: 000000320743.jpg
[239/500] Processing: 000000123213.jpg
[240/500] Processing: 000000465549.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 240 samples
[241/500] Processing: 000000101068.jpg
[242/500] Processing: 000000325031.jpg
[243/500] Processing: 000000034760.jpg
[244/500] Processing: 000000488673.jpg
[245/500] Processing: 000000517523.jpg
[246/500] Processing: 000000291861.jpg
[247/500] Processing: 000000352582.jpg
[248/500] Processing: 000000019432.jpg
[249/500] Processing: 000000566758.jpg
[250/500] Processing: 000000157928.jpg
[251/500] Processing: 000000340015.jpg
[252/500] Processing: 000000166747.jpg
[253/500] Processing: 000000500257.jpg
[254/500] Processing: 000000379332.jpg
[255/500] Processing: 000000055002.jpg
[256/500] Processing: 000000437331.jpg
[257/500] Processing: 000000380203.jpg
[258/500] Processing: 000000157767.jpg
[259/500] Processing: 000000361621.jpg
[260/500] Processing: 000000509260.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 260 samples
[261/500] Processing: 000000348488.jpg
[262/500] Processing: 000000402433.jpg
[263/500] Processing: 000000172330.jpg
[264/500] Processing: 000000546659.jpg
[265/500] Processing: 000000026465.jpg
[266/500] Processing: 000000054605.jpg
[267/500] Processing: 000000032735.jpg
[268/500] Processing: 000000353970.jpg
[269/500] Processing: 000000255664.jpg
[270/500] Processing: 000000481386.jpg
[271/500] Processing: 000000297084.jpg
[272/500] Processing: 000000356968.jpg
[273/500] Processing: 000000283037.jpg
[274/500] Processing: 000000303818.jpg
[275/500] Processing: 000000060507.jpg
[276/500] Processing: 000000245320.jpg
[277/500] Processing: 000000236592.jpg
[278/500] Processing: 000000176857.jpg
[279/500] Processing: 000000357903.jpg
[280/500] Processing: 000000519208.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 280 samples
[281/500] Processing: 000000024567.jpg
[282/500] Processing: 000000336232.jpg
[283/500] Processing: 000000565045.jpg
[284/500] Processing: 000000161609.jpg
[285/500] Processing: 000000205834.jpg
[286/500] Processing: 000000015335.jpg
[287/500] Processing: 000000446651.jpg
[288/500] Processing: 000000452891.jpg
[289/500] Processing: 000000189436.jpg
[290/500] Processing: 000000496597.jpg
[291/500] Processing: 000000395180.jpg
[292/500] Processing: 000000012748.jpg
[293/500] Processing: 000000411774.jpg
[294/500] Processing: 000000416451.jpg
[295/500] Processing: 000000230008.jpg
[296/500] Processing: 000000065350.jpg
[297/500] Processing: 000000129945.jpg
[298/500] Processing: 000000016228.jpg
[299/500] Processing: 000000125245.jpg
[300/500] Processing: 000000500049.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 300 samples
[301/500] Processing: 000000122166.jpg
[302/500] Processing: 000000503755.jpg
[303/500] Processing: 000000110884.jpg
[304/500] Processing: 000000235784.jpg
[305/500] Processing: 000000489339.jpg
[306/500] Processing: 000000306893.jpg
[307/500] Processing: 000000471756.jpg
[308/500] Processing: 000000162858.jpg
[309/500] Processing: 000000024610.jpg
[310/500] Processing: 000000386277.jpg
[311/500] Processing: 000000084170.jpg
[312/500] Processing: 000000047121.jpg
[313/500] Processing: 000000198928.jpg
[314/500] Processing: 000000377814.jpg
[315/500] Processing: 000000261732.jpg
[316/500] Processing: 000000425226.jpg
[317/500] Processing: 000000548246.jpg
[318/500] Processing: 000000459662.jpg
[319/500] Processing: 000000569565.jpg
[320/500] Processing: 000000150726.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 320 samples
[321/500] Processing: 000000370900.jpg
[322/500] Processing: 000000047819.jpg
[323/500] Processing: 000000072813.jpg
[324/500] Processing: 000000527695.jpg
[325/500] Processing: 000000535306.jpg
[326/500] Processing: 000000156372.jpg
[327/500] Processing: 000000052996.jpg
[328/500] Processing: 000000506707.jpg
[329/500] Processing: 000000095843.jpg
[330/500] Processing: 000000526392.jpg
[331/500] Processing: 000000450758.jpg
[332/500] Processing: 000000153299.jpg
[333/500] Processing: 000000579635.jpg
[334/500] Processing: 000000125936.jpg
[335/500] Processing: 000000151962.jpg
[336/500] Processing: 000000292908.jpg
[337/500] Processing: 000000236730.jpg
[338/500] Processing: 000000135673.jpg
[339/500] Processing: 000000559956.jpg
[340/500] Processing: 000000149375.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 340 samples
[341/500] Processing: 000000520009.jpg
[342/500] Processing: 000000054931.jpg
[343/500] Processing: 000000507667.jpg
[344/500] Processing: 000000168337.jpg
[345/500] Processing: 000000118209.jpg
[346/500] Processing: 000000062353.jpg
[347/500] Processing: 000000533493.jpg
[348/500] Processing: 000000232348.jpg
[349/500] Processing: 000000240023.jpg
[350/500] Processing: 000000199551.jpg
[351/500] Processing: 000000223188.jpg
[352/500] Processing: 000000515577.jpg
[353/500] Processing: 000000105014.jpg
[354/500] Processing: 000000250127.jpg
[355/500] Processing: 000000164883.jpg
[356/500] Processing: 000000563702.jpg
[357/500] Processing: 000000054164.jpg
[358/500] Processing: 000000036861.jpg
[359/500] Processing: 000000163057.jpg
[360/500] Processing: 000000171190.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 360 samples
[361/500] Processing: 000000474167.jpg
[362/500] Processing: 000000334555.jpg
[363/500] Processing: 000000111036.jpg
[364/500] Processing: 000000042102.jpg
[365/500] Processing: 000000466125.jpg
[366/500] Processing: 000000312586.jpg
[367/500] Processing: 000000486479.jpg
[368/500] Processing: 000000084664.jpg
[369/500] Processing: 000000276804.jpg
[370/500] Processing: 000000292330.jpg
[371/500] Processing: 000000445439.jpg
[372/500] Processing: 000000111609.jpg
[373/500] Processing: 000000002006.jpg
[374/500] Processing: 000000323496.jpg
[375/500] Processing: 000000049759.jpg
[376/500] Processing: 000000486104.jpg
[377/500] Processing: 000000281447.jpg
[378/500] Processing: 000000574810.jpg
[379/500] Processing: 000000105264.jpg
[380/500] Processing: 000000022892.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 380 samples
[381/500] Processing: 000000219440.jpg
[382/500] Processing: 000000213593.jpg
[383/500] Processing: 000000197796.jpg
[384/500] Processing: 000000083531.jpg
[385/500] Processing: 000000560371.jpg
[386/500] Processing: 000000168974.jpg
[387/500] Processing: 000000078823.jpg
[388/500] Processing: 000000579307.jpg
[389/500] Processing: 000000376278.jpg
[390/500] Processing: 000000420472.jpg
[391/500] Processing: 000000246883.jpg
[392/500] Processing: 000000015597.jpg
[393/500] Processing: 000000192047.jpg
[394/500] Processing: 000000181499.jpg
[395/500] Processing: 000000158227.jpg
[396/500] Processing: 000000058384.jpg
[397/500] Processing: 000000231527.jpg
[398/500] Processing: 000000571804.jpg
[399/500] Processing: 000000162415.jpg
[400/500] Processing: 000000521231.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 400 samples
[401/500] Processing: 000000072281.jpg
[402/500] Processing: 000000357060.jpg
[403/500] Processing: 000000544565.jpg
[404/500] Processing: 000000039785.jpg
[405/500] Processing: 000000410510.jpg
[406/500] Processing: 000000308476.jpg
[407/500] Processing: 000000349837.jpg
[408/500] Processing: 000000154339.jpg
[409/500] Processing: 000000055022.jpg
[410/500] Processing: 000000262487.jpg
[411/500] Processing: 000000107851.jpg
[412/500] Processing: 000000025181.jpg
[413/500] Processing: 000000005503.jpg
[414/500] Processing: 000000068286.jpg
[415/500] Processing: 000000184384.jpg
[416/500] Processing: 000000033221.jpg
[417/500] Processing: 000000058655.jpg
[418/500] Processing: 000000039956.jpg
[419/500] Processing: 000000464251.jpg
[420/500] Processing: 000000331569.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 420 samples
[421/500] Processing: 000000158945.jpg
[422/500] Processing: 000000122046.jpg
[423/500] Processing: 000000364166.jpg
[424/500] Processing: 000000348481.jpg
[425/500] Processing: 000000257370.jpg
[426/500] Processing: 000000513283.jpg
[427/500] Processing: 000000221693.jpg
[428/500] Processing: 000000188465.jpg
[429/500] Processing: 000000557672.jpg
[430/500] Processing: 000000396200.jpg
[431/500] Processing: 000000055150.jpg
[432/500] Processing: 000000489046.jpg
[433/500] Processing: 000000184762.jpg
[434/500] Processing: 000000519764.jpg
[435/500] Processing: 000000186637.jpg
[436/500] Processing: 000000309495.jpg
[437/500] Processing: 000000346707.jpg
[438/500] Processing: 000000184611.jpg
[439/500] Processing: 000000115870.jpg
[440/500] Processing: 000000072795.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 440 samples
[441/500] Processing: 000000074860.jpg
[442/500] Processing: 000000508602.jpg
[443/500] Processing: 000000172595.jpg
[444/500] Processing: 000000217872.jpg
[445/500] Processing: 000000451150.jpg
[446/500] Processing: 000000483531.jpg
[447/500] Processing: 000000547383.jpg
[448/500] Processing: 000000515982.jpg
[449/500] Processing: 000000020571.jpg
[450/500] Processing: 000000549674.jpg
[451/500] Processing: 000000462629.jpg
[452/500] Processing: 000000067180.jpg
[453/500] Processing: 000000435003.jpg
[454/500] Processing: 000000134034.jpg
[455/500] Processing: 000000110999.jpg
[456/500] Processing: 000000297830.jpg
[457/500] Processing: 000000198510.jpg
[458/500] Processing: 000000509258.jpg
[459/500] Processing: 000000034873.jpg
[460/500] Processing: 000000182417.jpg
Saved to /kaggle/working/phi_vs_llava_rag_500_mscoco.csv at 460 samples
[461/500] Processing: 000000217285.jpg
[462/500] Processing: 000000578489.jpg
[463/500] Processing: 000000122969.jpg
[464/500] Processing: 000000021604.jpg
[465/500] Processing: 000000535094.jpg
[466/500] Processing: 000000575081.jpg
[467/500] Processing: 000000565153.jpg
[468/500] Processing: 000000140640.jpg
[469/500] Processing: 000000063552.jpg
[470/500] Processing: 000000167128.jpg
[471/500] Processing: 000000281759.jpg
[472/500] Processing: 000000091921.jpg
[473/500] Processing: 000000478136.jpg
[474/500] Processing: 000000378453.jpg

,image_name,image_path,retrieved_captions,retrieved_scores,retrieved_image_names,hit@1,hit@5,hit@10,raw_phi,answer_phi,raw_llava,answer_llava
0,000000328238.jpg,/kaggle/input/datasets/saptarshim596/val2017-m...,[A guy gets ready to throw a Frisbee during a ...,"[0.38285431265830994, 0.3726266920566559, 0.37...","[000000401244.jpg, 000000409198.jpg, 000000352...",0,0,0,A man holding a frisbee prepares to throw it.,A man holding a frisbee prepares to throw it.,A man in a blue shirt and white hat is about t...,A man in a blue shirt and white hat is about t...
1,000000074256.jpg,/kaggle/input/datasets/saptarshim596/val2017-m...,"[Elderly women debark a bus at a station. , A ...","[0.3621743619441986, 0.3537268340587616, 0.331...","[000000507797.jpg, 000000517069.jpg, 000000052...",0,0,0,Two women are standing at a bus stop waiting t...,Two women are standing at a bus stop waiting t...,Two women are standing at a bus stop.,Two women are standing at a bus stop.
2,000000022192.jpg,/kaggle/input/datasets/saptarshim596/val2017-m...,"[A dog sitting on a bed covered with clothing,...","[0.366780549287796, 0.35598838329315186, 0.350...","[000000022192.jpg, 000000022192.jpg, 000000022...",1,1,1,"A dog sitting on a bed covered with clothing, ...","A dog sitting on a bed covered with clothing, ...","A dog sitting on a bed covered with clothing, ...","A dog sitting on a bed covered with clothing, ..."
3,000000531495.jpg,/kaggle/input/datasets/saptarshim596/val2017-m...,[Looking out over a bay with many tourist boat...,"[0.294355183839798, 0.29095879197120667, 0.282...","[000000050006.jpg, 000000490470.jpg, 000000328...",0,1,1,A harbor with several boats floating in it.,A harbor with several boats floating in it.,A harbor with several boats floating in it.,A harbor with several boats floating in it.
4,000000236426.jpg,/kaggle/input/datasets/saptarshim596/val2017-m...,[A white-clad tennis player hurls a ball upwar...,"[0.32634979486465454, 0.3248714506626129, 0.32...","[000000269121.jpg, 000000261097.jpg, 000000080...",0,0,0,A man in a white tennis outfit swinging his ra...,A man in a white tennis outfit swinging his ra...,A man in a white shirt and shorts is playing t...,A man in a white shirt and shorts is playing t...

### Analyzing the output quality of the models

In [27]:
from collections import defaultdict
import pandas as pd

gt_map = defaultdict(list)
for _, row in df.iterrows():
    gt_map[str(row["image_name"]).strip()].append(str(row["comment"]).strip())

df_phi_llava["references"] = df_phi_llava["image_name"].map(gt_map)
df_eval_models = df_phi_llava[df_phi_llava["references"].notna()].copy()

print("Rows for evaluation:", len(df_eval_models))

Rows for evaluation: 500

In [28]:
import numpy as np
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

smooth = SmoothingFunction().method1
rouge = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

def bleu_against_refs(pred, refs):
    pred_tokens = pred.split()
    ref_tokens = [r.split() for r in refs]
    return sentence_bleu(ref_tokens, pred_tokens, smoothing_function=smooth)

def best_rouge_against_refs(pred, refs):
    best = {"rouge1": 0.0, "rouge2": 0.0, "rougeL": 0.0}
    for ref in refs:
        scores = rouge.score(ref, pred)
        for k in best:
            best[k] = max(best[k], scores[k].fmeasure)
    return best

In [29]:
from PIL import Image
import torch
import open_clip

@torch.no_grad()
def compute_clipscore_single(img_path, caption):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess(img).unsqueeze(0).to(device)

    img_feat = clip_model.encode_image(img_in)
    img_feat = img_feat / img_feat.norm(dim=-1, keepdim=True)

    tokens = open_clip.tokenize([caption]).to(device)
    txt_feat = clip_model.encode_text(tokens)
    txt_feat = txt_feat / txt_feat.norm(dim=-1, keepdim=True)

    return (img_feat * txt_feat).sum(dim=-1).item()

In [30]:
def evaluate_model_outputs(df_eval, answer_col):
    bleu_scores = []
    rouge1_scores, rouge2_scores, rougeL_scores = [], [], []
    clip_scores = []

    for i, row in enumerate(df_eval.itertuples(index=False)):
        refs = row.references
        pred = str(getattr(row, answer_col)).strip()

        bleu_scores.append(bleu_against_refs(pred, refs))

        rs = best_rouge_against_refs(pred, refs)
        rouge1_scores.append(rs["rouge1"])
        rouge2_scores.append(rs["rouge2"])
        rougeL_scores.append(rs["rougeL"])

        clip_scores.append(compute_clipscore_single(row.image_path, pred))

        if (i + 1) % 20 == 0:
            print(f"Evaluated {i+1}/{len(df_eval)} for {answer_col}")

    return {
        "BLEU": bleu_scores,
        "ROUGE-1": rouge1_scores,
        "ROUGE-2": rouge2_scores,
        "ROUGE-L": rougeL_scores,
        "CLIPScore": clip_scores
    }

In [31]:
scores_phi = evaluate_model_outputs(df_eval_models, "answer_phi")
scores_llava = evaluate_model_outputs(df_eval_models, "answer_llava")

Evaluated 20/500 for answer_phi
Evaluated 40/500 for answer_phi
Evaluated 60/500 for answer_phi
Evaluated 80/500 for answer_phi
Evaluated 100/500 for answer_phi
Evaluated 120/500 for answer_phi
Evaluated 140/500 for answer_phi
Evaluated 160/500 for answer_phi
Evaluated 180/500 for answer_phi
Evaluated 200/500 for answer_phi
Evaluated 220/500 for answer_phi
Evaluated 240/500 for answer_phi
Evaluated 260/500 for answer_phi
Evaluated 280/500 for answer_phi
Evaluated 300/500 for answer_phi
Evaluated 320/500 for answer_phi
Evaluated 340/500 for answer_phi
Evaluated 360/500 for answer_phi
Evaluated 380/500 for answer_phi
Evaluated 400/500 for answer_phi
Evaluated 420/500 for answer_phi
Evaluated 440/500 for answer_phi
Evaluated 460/500 for answer_phi
Evaluated 480/500 for answer_phi
Evaluated 500/500 for answer_phi
Evaluated 20/500 for answer_llava
Evaluated 40/500 for answer_llava
Evaluated 60/500 for answer_llava
Evaluated 80/500 for answer_llava
Evaluated 100/500 for answer_llava
Evaluated 120/500 for answer_llava
Evaluated 140/500 for answer_llava
Evaluated 160/500 for answer_llava
Evaluated 180/500 for answer_llava
Evaluated 200/500 for answer_llava
Evaluated 220/500 for answer_llava
Evaluated 240/500 for answer_llava
Evaluated 260/500 for answer_llava
Evaluated 280/500 for answer_llava
Evaluated 300/500 for answer_llava
Evaluated 320/500 for answer_llava
Evaluated 340/500 for answer_llava
Evaluated 360/500 for answer_llava
Evaluated 380/500 for answer_llava
Evaluated 400/500 for answer_llava
Evaluated 420/500 for answer_llava
Evaluated 440/500 for answer_llava
Evaluated 460/500 for answer_llava
Evaluated 480/500 for answer_llava
Evaluated 500/500 for answer_llava

In [32]:
df_eval_models["bleu_phi"] = scores_phi["BLEU"]
df_eval_models["rouge1_phi"] = scores_phi["ROUGE-1"]
df_eval_models["rouge2_phi"] = scores_phi["ROUGE-2"]
df_eval_models["rougeL_phi"] = scores_phi["ROUGE-L"]
df_eval_models["clipscore_phi"] = scores_phi["CLIPScore"]

df_eval_models["bleu_llava"] = scores_llava["BLEU"]
df_eval_models["rouge1_llava"] = scores_llava["ROUGE-1"]
df_eval_models["rouge2_llava"] = scores_llava["ROUGE-2"]
df_eval_models["rougeL_llava"] = scores_llava["ROUGE-L"]
df_eval_models["clipscore_llava"] = scores_llava["CLIPScore"]

In [33]:
def build_two_model_summary(scores1, scores2, model1_name="Phi", model2_name="LLaVA"):
    rows = []

    for metric in ["BLEU", "ROUGE-1", "ROUGE-2", "ROUGE-L", "CLIPScore"]:
        s1 = np.array(scores1[metric])
        s2 = np.array(scores2[metric])

        rows.append({
            "Metric": metric,
            model1_name: f"{s1.mean():.4f} ± {s1.std():.4f}",
            model2_name: f"{s2.mean():.4f} ± {s2.std():.4f}",
            "Gain (Phi-LLaVA)": s1.mean() - s2.mean()
        })

    return pd.DataFrame(rows)

In [34]:
summary_phi_vs_llava = build_two_model_summary(
    scores_phi,
    scores_llava,
    model1_name="Phi-3.5",
    model2_name="LLaVA-1.5-7B"
)

summary_phi_vs_llava

      Metric          Phi-3.5     LLaVA-1.5-7B  Gain (Phi-LLaVA)
0       BLEU  0.5090 ± 0.3893  0.4340 ± 0.3606          0.075029
1    ROUGE-1  0.7299 ± 0.2391  0.7070 ± 0.2180          0.022811
2    ROUGE-2  0.5773 ± 0.3450  0.5229 ± 0.3136          0.054479
3    ROUGE-L  0.7028 ± 0.2588  0.6747 ± 0.2358          0.028046
4  CLIPScore  0.3393 ± 0.0351  0.3313 ± 0.0385          0.008000

In [35]:
def print_model_improvements(scores1, scores2, model1_name="Phi", model2_name="LLaVA"):
    print(f"\n=== {model1_name} vs {model2_name} ===")
    for metric in ["BLEU", "ROUGE-1", "ROUGE-2", "ROUGE-L", "CLIPScore"]:
        m1 = np.mean(scores1[metric])
        m2 = np.mean(scores2[metric])
        print(f"{metric}: {model1_name} - {model2_name} = {m1 - m2:+.4f}")

In [36]:
print_model_improvements(scores_phi, scores_llava, "Phi-3.5", "LLaVA-1.5-7B")

=== Phi-3.5 vs LLaVA-1.5-7B ===
BLEU: Phi-3.5 - LLaVA-1.5-7B = +0.0750
ROUGE-1: Phi-3.5 - LLaVA-1.5-7B = +0.0228
ROUGE-2: Phi-3.5 - LLaVA-1.5-7B = +0.0545
ROUGE-L: Phi-3.5 - LLaVA-1.5-7B = +0.0280
CLIPScore: Phi-3.5 - LLaVA-1.5-7B = +0.0080

### Conducting paired significance test to see whether the result is significant

In [37]:
!pip install scipy

Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from scipy) (2.0.2)

In [38]:
from scipy.stats import ttest_rel

def paired_significance_test(scores1, scores2, model1_name="Phi", model2_name="LLaVA"):
    rows = []

    for metric in ["BLEU", "ROUGE-1", "ROUGE-2", "ROUGE-L", "CLIPScore"]:
        stat, pval = ttest_rel(scores1[metric], scores2[metric])

        rows.append({
            "Metric": metric,
            "p-value": pval,
            "Significant (<0.05)": pval < 0.05
        })

    return pd.DataFrame(rows)

In [39]:
ttest_phi_vs_llava = paired_significance_test(
    scores_phi,
    scores_llava,
    "Phi-3.5",
    "LLaVA-1.5-7B"
)

ttest_phi_vs_llava

      Metric       p-value  Significant (<0.05)
0       BLEU  4.134686e-06                 True
1    ROUGE-1  2.245471e-02                 True
2    ROUGE-2  1.582618e-04                 True
3    ROUGE-L  8.761427e-03                 True
4  CLIPScore  4.453916e-09                 True

In [40]:
summary_phi_vs_llava.to_csv("/kaggle/working/summary_phi_vs_llava_mscoco.csv", index=False)
ttest_phi_vs_llava.to_csv("/kaggle/working/ttest_phi_vs_llava_mscoco.csv", index=False)
df_eval_models.to_csv("/kaggle/working/df_eval_phi_vs_llava_mscoco.csv", index=False)