In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O

In [2]:
!pip uninstall -y transformers accelerate -q
!pip install -q transformers==4.43.0 accelerate==0.30.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 69.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 kB 23.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 37.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 95.1 MB/s eta 0:00:00

### Importing the flickr30k dataset

In [3]:
import os

BASE = "/kaggle/input/datasets/hsankesara/flickr-image-dataset/flickr30k_images"
IMG_DIR = os.path.join(BASE, "flickr30k_images")
CAPTION_FILE = "/kaggle/input/datasets/hsankesara/flickr-image-dataset/flickr30k_images/results.csv"

print("Image folder:", IMG_DIR)
print("Caption file:", CAPTION_FILE)

Image folder: /kaggle/input/datasets/hsankesara/flickr-image-dataset/flickr30k_images/flickr30k_images
Caption file: /kaggle/input/datasets/hsankesara/flickr-image-dataset/flickr30k_images/results.csv

In [4]:
print("Number of images:", len(os.listdir(IMG_DIR)))
print(os.listdir(IMG_DIR)[:10])

Number of images: 31785
['2715746315.jpg', '3463034205.jpg', '268704620.jpg', '2673564214.jpg', '7535037918.jpg', '4912369161.jpg', '4828071602.jpg', '6802728196.jpg', '3346289227.jpg', '3217056901.jpg']

In [5]:
import pandas as pd

df = pd.read_csv(CAPTION_FILE, sep='|')
df.head()

,image_name,comment_number,comment
0,1000092795.jpg,0,Two young guys with shaggy hair look at their...
1,1000092795.jpg,1,"Two young , White males are outside near many..."
2,1000092795.jpg,2,Two men in green shirts are standing in a yard .
3,1000092795.jpg,3,A man in a blue shirt standing in a garden .
4,1000092795.jpg,4,Two friends enjoy time spent together .

In [6]:
df.columns = df.columns.str.strip()

In [7]:
!pip -q install open_clip_torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 23.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 3.6 MB/s eta 0:00:00

In [8]:
import torch
import open_clip
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

clip_model, _, preprocess = open_clip.create_model_and_transforms(
    "ViT-B-32",
    pretrained="laion2b_s34b_b79k"
)
tokenizer = open_clip.get_tokenizer("ViT-B-32")

clip_model = clip_model.to(device).eval()
print("Device:", device)

open_clip_model.safetensors:   0%|          | 0.00/605M [00:00<?, ?B/s]

Device: cuda

### Using all captions

In [9]:
CAPTION_N = 200000

cap_df = df.sample(n=min(CAPTION_N, len(df)), random_state=42).reset_index(drop=True)
captions = cap_df["comment"].astype(str).tolist()

print("Captions in pool:", len(captions))

Captions in pool: 158915

In [10]:
@torch.no_grad()
def encode_texts(text_list, batch_size=256):
    embs = []
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        tokens = tokenizer(batch).to(device)
        feat = clip_model.encode_text(tokens)
        feat = feat / feat.norm(dim=-1, keepdim=True)
        embs.append(feat.cpu())
    return torch.cat(embs, dim=0)

In [11]:
from PIL import Image
import matplotlib.pyplot as plt
import os, random

@torch.no_grad()
def encode_image(img_path):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess(img).unsqueeze(0).to(device)
    feat = clip_model.encode_image(img_in)
    feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.cpu(), img

In [12]:
import transformers, accelerate, torch
print(transformers.__version__)
print(accelerate.__version__)
print(torch.__version__)

4.43.0
0.30.0
2.9.0+cu126

### Setting the LLM(Phi-3.5-vision-instruct) model

In [13]:
import os
import torch
from transformers import AutoConfig, AutoProcessor, AutoModelForCausalLM
from huggingface_hub import login

os.environ["HF_HOME"] = "/kaggle/working/hf_cache"
os.environ["TRANSFORMERS_CACHE"] = "/kaggle/working/hf_cache"

# Login
login(token="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")

VLM_NAME = "microsoft/Phi-3.5-vision-instruct"

config = AutoConfig.from_pretrained(
    VLM_NAME,
    trust_remote_code=True
)
config._attn_implementation = "eager"

processor = AutoProcessor.from_pretrained(
    VLM_NAME,
    trust_remote_code=True  
)

phi_model = AutoModelForCausalLM.from_pretrained(
    VLM_NAME,
    config=config,
    trust_remote_code=True,
    device_map="auto",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
).eval()

2026-03-29 12:31:29.132239: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1774787489.321423      24 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1774787489.376063      24 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1774787489.857328      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774787489.857366      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774787489.857368      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1774787489.857371      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

config.json: 0.00B [00:00, ?B/s]

configuration_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- configuration_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

processor_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

processing_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- processing_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
/usr/local/lib/python3.12/dist-packages/transformers/models/auto/image_processing_auto.py:513: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(

preprocessor_config.json:   0%|          | 0.00/442 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/670 [00:00<?, ?B/s]

modeling_phi3_v.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/Phi-3.5-vision-instruct:
- modeling_phi3_v.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.35G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/136 [00:00<?, ?B/s]

### Analysis of response quality for hit@1, hit@5 and hit@10

In [14]:
CAPTION_N = 200000

cap_df = df.sample(n=min(CAPTION_N, len(df)), random_state=42).reset_index(drop=True)

captions = cap_df["comment"].astype(str).tolist()

print("Captions in pool:", len(captions))

Captions in pool: 158915

In [15]:
@torch.no_grad()
def encode_captions(text_list, batch_size=256):
    embs = []

    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]

        tokens = open_clip.tokenize(batch).to(device)

        feat = clip_model.encode_text(tokens)

        # Normalize (important for cosine similarity)
        feat = feat / feat.norm(dim=-1, keepdim=True)

        embs.append(feat.cpu())

        if i % (batch_size * 10) == 0:
            print(f"Processed {i}/{len(text_list)} captions")

    return torch.cat(embs, dim=0)

In [16]:
caption_embs = encode_captions(captions, batch_size=256)

print("Caption embeddings:", caption_embs.shape)

Processed 0/158915 captions
Processed 2560/158915 captions
Processed 5120/158915 captions
Processed 7680/158915 captions
Processed 10240/158915 captions
Processed 12800/158915 captions
Processed 15360/158915 captions
Processed 17920/158915 captions
Processed 20480/158915 captions
Processed 23040/158915 captions
Processed 25600/158915 captions
Processed 28160/158915 captions
Processed 30720/158915 captions
Processed 33280/158915 captions
Processed 35840/158915 captions
Processed 38400/158915 captions
Processed 40960/158915 captions
Processed 43520/158915 captions
Processed 46080/158915 captions
Processed 48640/158915 captions
Processed 51200/158915 captions
Processed 53760/158915 captions
Processed 56320/158915 captions
Processed 58880/158915 captions
Processed 61440/158915 captions
Processed 64000/158915 captions
Processed 66560/158915 captions
Processed 69120/158915 captions
Processed 71680/158915 captions
Processed 74240/158915 captions
Processed 76800/158915 captions
Processed 79360/158915 captions
Processed 81920/158915 captions
Processed 84480/158915 captions
Processed 87040/158915 captions
Processed 89600/158915 captions
Processed 92160/158915 captions
Processed 94720/158915 captions
Processed 97280/158915 captions
Processed 99840/158915 captions
Processed 102400/158915 captions
Processed 104960/158915 captions
Processed 107520/158915 captions
Processed 110080/158915 captions
Processed 112640/158915 captions
Processed 115200/158915 captions
Processed 117760/158915 captions
Processed 120320/158915 captions
Processed 122880/158915 captions
Processed 125440/158915 captions
Processed 128000/158915 captions
Processed 130560/158915 captions
Processed 133120/158915 captions
Processed 135680/158915 captions
Processed 138240/158915 captions
Processed 140800/158915 captions
Processed 143360/158915 captions
Processed 145920/158915 captions
Processed 148480/158915 captions
Processed 151040/158915 captions
Processed 153600/158915 captions
Processed 156160/158915 captions
Processed 158720/158915 captions
Caption embeddings: torch.Size([158915, 512])

In [17]:
torch.save(caption_embs, "/kaggle/working/caption_embs_all.pt")

In [18]:
caption_embs = torch.load("/kaggle/working/caption_embs_all.pt")

In [19]:
import os
import random
import re
import torch
import pandas as pd
from PIL import Image


def clean_answer(text):
    text = text.strip()

    stop_markers = [
        "# User", "# Assistant", "# Input", "# Output", "##",
        "<|user|>", "<|assistant|>", "<|end|>"
    ]

    for marker in stop_markers:
        if marker in text:
            text = text.split(marker)[0].strip()

    sentences = re.split(r'(?<=[.!?])\s+', text)
    return " ".join(sentences[:1]).strip()


@torch.no_grad()
def encode_image(img_path):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess(img).unsqueeze(0).to(device)
    feat = clip_model.encode_image(img_in)
    feat = feat / feat.norm(dim=-1, keepdim=True)
    return feat.cpu(), img


def get_random_image_embeddings(img_dir, num_samples=10, seed=42):
    random.seed(seed)

    all_images = [
        os.path.join(img_dir, f)
        for f in os.listdir(img_dir)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    if not all_images:
        raise ValueError(f"No image files found in: {img_dir}")

    sampled_images = random.sample(all_images, min(num_samples, len(all_images)))

    embeddings = []
    image_objects = []
    image_paths = []

    for img_path in sampled_images:
        feat, img = encode_image(img_path)
        embeddings.append(feat)
        image_objects.append(img)
        image_paths.append(img_path)

    embeddings = torch.cat(embeddings, dim=0)   # (N, D)
    return embeddings, image_objects, image_paths

In [20]:
def retrieve_topk_captions_for_image(image_emb, caption_embs, captions, caption_image_names, k=10):
    """
    image_emb: tensor of shape (D,) or (1, D)
    caption_embs: tensor of shape (M, D)
    captions: list[str]
    caption_image_names: list[str]
    """
    if image_emb.dim() == 1:
        image_emb = image_emb.unsqueeze(0)

    sims = image_emb @ caption_embs.T
    top_scores, top_idx = torch.topk(sims, k=min(k, len(captions)), dim=1)

    results = []
    for score, idx in zip(top_scores[0].tolist(), top_idx[0].tolist()):
        results.append({
            "score": score,
            "caption": captions[idx],
            "caption_image_name": caption_image_names[idx]
        })

    return results

In [21]:

@torch.no_grad()
def generate_with_rag(img_path, retrieved_caps, phi_model, processor, max_new_tokens=25):
    image = Image.open(img_path).convert("RGB")

    context_block = "\n".join([f"- {cap}" for _, cap in retrieved_caps])

    prompt = f"""<|user|>
<|image_1|>
Describe this image in one sentence.

Helpful retrieved captions:
{context_block}

Only answer with the description sentence.
<|end|>
<|assistant|>
"""

    inputs = processor(
        text=prompt,
        images=image,
        return_tensors="pt"
    )

    for k, v in inputs.items():
        if hasattr(v, "to"):
            inputs[k] = v.to(phi_model.device)

    outputs = phi_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        use_cache=False,
        eos_token_id=processor.tokenizer.eos_token_id,
        pad_token_id=processor.tokenizer.eos_token_id
    )

    generated_ids = outputs[:, inputs["input_ids"].shape[1]:]

    raw_answer = processor.tokenizer.decode(
        generated_ids[0],
        skip_special_tokens=True
    ).strip()

    return raw_answer, clean_answer(raw_answer)

In [22]:
import os
import pandas as pd

def run_rag_quality_vs_recall_pipeline(
    img_dir,
    caption_embs,
    captions,
    caption_image_names,
    phi_model,
    processor,
    num_samples=100,
    seed=42,
    k=10,
    save_every=25,
    save_path="/kaggle/working/rag_quality_vs_recall.csv"
):
    sampled_img_embs, _, sampled_img_paths = get_random_image_embeddings(
        img_dir,
        num_samples=num_samples,
        seed=seed
    )

    outputs = []

    for i, img_path in enumerate(sampled_img_paths):
        image_name = os.path.basename(img_path)
        print(f"[{i+1}/{len(sampled_img_paths)}] Processing: {image_name}")

        image_emb = sampled_img_embs[i]

        retrieved = retrieve_topk_captions_for_image(
            image_emb=image_emb,
            caption_embs=caption_embs,
            captions=captions,
            caption_image_names=caption_image_names,
            k=k
        )

        retrieved_caps = [(x["score"], x["caption"]) for x in retrieved]
        retrieved_names = [x["caption_image_name"] for x in retrieved]

        hit1 = int(any(name == image_name for name in retrieved_names[:1]))
        hit5 = int(any(name == image_name for name in retrieved_names[:5]))
        hit10 = int(any(name == image_name for name in retrieved_names[:10]))

        raw_rag, ans_rag = generate_with_rag(
            img_path=img_path,
            retrieved_caps=retrieved_caps,
            phi_model=phi_model,
            processor=processor
        )

        outputs.append({
            "image_name": image_name,
            "image_path": img_path,
            "retrieved_captions": [x["caption"] for x in retrieved],
            "retrieved_scores": [x["score"] for x in retrieved],
            "retrieved_image_names": retrieved_names,
            "hit@1": hit1,
            "hit@5": hit5,
            "hit@10": hit10,
            "raw_rag": raw_rag,
            "answer_rag": ans_rag
        })

        if (i + 1) % save_every == 0 or (i + 1) == len(sampled_img_paths):
            pd.DataFrame(outputs).to_csv(save_path, index=False)
            print(f"Saved to {save_path} at {i+1} samples")

    return pd.DataFrame(outputs)

In [23]:
caption_image_names = cap_df["image_name"].astype(str).tolist()

In [24]:
df_rag_recall = run_rag_quality_vs_recall_pipeline(
    img_dir=IMG_DIR,
    caption_embs=caption_embs,
    captions=captions,
    caption_image_names=caption_image_names,
    phi_model=phi_model,
    processor=processor,
    num_samples=200,
    seed=123,
    k=10,
    save_every=50,
    save_path="/kaggle/working/rag_quality_vs_recall_200.csv"
)

df_rag_recall.head()

The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.

[1/200] Processing: 3202798691.jpg

WARNING:transformers_modules.microsoft.Phi-3.5-vision-instruct.12b77fb40b63a2c73c68243d3f767aab688a1b2a.modeling_phi3_v:You are not running the flash-attention implementation, expect numerical differences.

[2/200] Processing: 4888378326.jpg
[3/200] Processing: 4196910882.jpg
[4/200] Processing: 2437917174.jpg
[5/200] Processing: 3246788996.jpg
[6/200] Processing: 1507563902.jpg
[7/200] Processing: 4756096577.jpg
[8/200] Processing: 2705888144.jpg
[9/200] Processing: 4636627093.jpg
[10/200] Processing: 9726060.jpg
[11/200] Processing: 633456174.jpg
[12/200] Processing: 411175971.jpg
[13/200] Processing: 3694093650.jpg
[14/200] Processing: 3591094476.jpg
[15/200] Processing: 1918894054.jpg
[16/200] Processing: 439569646.jpg
[17/200] Processing: 512761651.jpg
[18/200] Processing: 531347711.jpg
[19/200] Processing: 5651514000.jpg
[20/200] Processing: 3265209567.jpg
[21/200] Processing: 7249180494.jpg
[22/200] Processing: 4329159924.jpg
[23/200] Processing: 4477151562.jpg
[24/200] Processing: 2905975229.jpg
[25/200] Processing: 52226520.jpg
[26/200] Processing: 8038838476.jpg
[27/200] Processing: 7001949951.jpg
[28/200] Processing: 2908391223.jpg
[29/200] Processing: 3057497487.jpg
[30/200] Processing: 4929731785.jpg
[31/200] Processing: 4538960982.jpg
[32/200] Processing: 6867197342.jpg
[33/200] Processing: 6082254728.jpg
[34/200] Processing: 2906759254.jpg
[35/200] Processing: 2507431891.jpg
[36/200] Processing: 331023909.jpg
[37/200] Processing: 467658231.jpg
[38/200] Processing: 4556002396.jpg
[39/200] Processing: 3225058391.jpg
[40/200] Processing: 4717966711.jpg
[41/200] Processing: 6887014469.jpg
[42/200] Processing: 4074803780.jpg
[43/200] Processing: 3444982197.jpg
[44/200] Processing: 1806580620.jpg
[45/200] Processing: 1105137588.jpg
[46/200] Processing: 2656110989.jpg
[47/200] Processing: 7576330234.jpg
[48/200] Processing: 4942012087.jpg
[49/200] Processing: 2609133063.jpg
[50/200] Processing: 3336374196.jpg
Saved to /kaggle/working/rag_quality_vs_recall_200.csv at 50 samples
[51/200] Processing: 4718615348.jpg
[52/200] Processing: 5635975939.jpg
[53/200] Processing: 3574962735.jpg
[54/200] Processing: 3251648670.jpg
[55/200] Processing: 3487820317.jpg
[56/200] Processing: 3698944019.jpg
[57/200] Processing: 4168954238.jpg
[58/200] Processing: 5807099586.jpg
[59/200] Processing: 4961508842.jpg
[60/200] Processing: 3302986588.jpg
[61/200] Processing: 6953298252.jpg
[62/200] Processing: 4103240621.jpg
[63/200] Processing: 367248403.jpg
[64/200] Processing: 233581449.jpg
[65/200] Processing: 2766926202.jpg
[66/200] Processing: 44201115.jpg
[67/200] Processing: 3264464625.jpg
[68/200] Processing: 4086326509.jpg
[69/200] Processing: 2378149488.jpg
[70/200] Processing: 4859789355.jpg
[71/200] Processing: 345684566.jpg
[72/200] Processing: 5622966650.jpg
[73/200] Processing: 4727583716.jpg
[74/200] Processing: 7754829172.jpg
[75/200] Processing: 2788183053.jpg
[76/200] Processing: 2686141763.jpg
[77/200] Processing: 7428316382.jpg
[78/200] Processing: 2236895638.jpg
[79/200] Processing: 5648321.jpg
[80/200] Processing: 511400700.jpg
[81/200] Processing: 7779718252.jpg
[82/200] Processing: 4724995701.jpg
[83/200] Processing: 3825049160.jpg
[84/200] Processing: 4744759921.jpg
[85/200] Processing: 6954663021.jpg
[86/200] Processing: 2867460039.jpg
[87/200] Processing: 4796827555.jpg
[88/200] Processing: 401649634.jpg
[89/200] Processing: 3234375022.jpg
[90/200] Processing: 2631353232.jpg
[91/200] Processing: 4319855412.jpg
[92/200] Processing: 4566219691.jpg
[93/200] Processing: 64086350.jpg
[94/200] Processing: 4845542946.jpg
[95/200] Processing: 1660269454.jpg
[96/200] Processing: 3109124656.jpg
[97/200] Processing: 3193029429.jpg
[98/200] Processing: 4694601786.jpg
[99/200] Processing: 6198563920.jpg
[100/200] Processing: 4347559524.jpg
Saved to /kaggle/working/rag_quality_vs_recall_200.csv at 100 samples
[101/200] Processing: 3827161885.jpg
[102/200] Processing: 4445607388.jpg
[103/200] Processing: 3469584002.jpg
[104/200] Processing: 356478206.jpg
[105/200] Processing: 370614351.jpg
[106/200] Processing: 85519095.jpg
[107/200] Processing: 2708775214.jpg
[108/200] Processing: 3565917449.jpg
[109/200] Processing: 311380477.jpg
[110/200] Processing: 56012054.jpg
[111/200] Processing: 7411114322.jpg
[112/200] Processing: 4623878206.jpg
[113/200] Processing: 2063399864.jpg
[114/200] Processing: 4327514739.jpg
[115/200] Processing: 3214333978.jpg
[116/200] Processing: 2359100647.jpg
[117/200] Processing: 3668900592.jpg
[118/200] Processing: 2542299880.jpg
[119/200] Processing: 513831663.jpg
[120/200] Processing: 365504466.jpg
[121/200] Processing: 7345543488.jpg
[122/200] Processing: 4860806028.jpg
[123/200] Processing: 4540109233.jpg
[124/200] Processing: 2279416167.jpg
[125/200] Processing: 4062486051.jpg
[126/200] Processing: 3329961466.jpg
[127/200] Processing: 5068219705.jpg
[128/200] Processing: 2094076980.jpg
[129/200] Processing: 3249278583.jpg
[130/200] Processing: 3197917064.jpg
[131/200] Processing: 2097398349.jpg
[132/200] Processing: 4926723.jpg
[133/200] Processing: 3748039603.jpg
[134/200] Processing: 4811455038.jpg
[135/200] Processing: 6848901011.jpg
[136/200] Processing: 316577571.jpg
[137/200] Processing: 2394003437.jpg
[138/200] Processing: 45935254.jpg
[139/200] Processing: 4892334228.jpg
[140/200] Processing: 4115212373.jpg
[141/200] Processing: 7102120965.jpg
[142/200] Processing: 4587901777.jpg
[143/200] Processing: 2737097000.jpg
[144/200] Processing: 3162442331.jpg
[145/200] Processing: 4455065396.jpg
[146/200] Processing: 1874617189.jpg
[147/200] Processing: 6307540579.jpg
[148/200] Processing: 4429660.jpg
[149/200] Processing: 3188587858.jpg
[150/200] Processing: 758921886.jpg
Saved to /kaggle/working/rag_quality_vs_recall_200.csv at 150 samples
[151/200] Processing: 4645242031.jpg
[152/200] Processing: 4732894483.jpg
[153/200] Processing: 2577450794.jpg
[154/200] Processing: 3689150386.jpg
[155/200] Processing: 3393152604.jpg
[156/200] Processing: 5491397203.jpg
[157/200] Processing: 2659606300.jpg
[158/200] Processing: 4937760948.jpg
[159/200] Processing: 58727908.jpg
[160/200] Processing: 191488669.jpg
[161/200] Processing: 3253257881.jpg
[162/200] Processing: 2407865161.jpg
[163/200] Processing: 4983959726.jpg
[164/200] Processing: 430803349.jpg
[165/200] Processing: 5220940345.jpg
[166/200] Processing: 3401437960.jpg
[167/200] Processing: 218096711.jpg
[168/200] Processing: 295402802.jpg
[169/200] Processing: 171134073.jpg
[170/200] Processing: 4717261252.jpg
[171/200] Processing: 4771148918.jpg
[172/200] Processing: 1043910339.jpg
[173/200] Processing: 543363241.jpg
[174/200] Processing: 4037128007.jpg
[175/200] Processing: 4469010721.jpg
[176/200] Processing: 2830073704.jpg
[177/200] Processing: 3590049329.jpg
[178/200] Processing: 4968714648.jpg
[179/200] Processing: 3555376013.jpg
[180/200] Processing: 4027160843.jpg
[181/200] Processing: 1299817309.jpg
[182/200] Processing: 1065323785.jpg
[183/200] Processing: 6857882214.jpg
[184/200] Processing: 4654264126.jpg
[185/200] Processing: 3397090388.jpg
[186/200] Processing: 1255846277.jpg
[187/200] Processing: 476765164.jpg
[188/200] Processing: 1196432301.jpg
[189/200] Processing: 2603792708.jpg
[190/200] Processing: 4937201390.jpg
[191/200] Processing: 3613424631.jpg
[192/200] Processing: 51900752.jpg
[193/200] Processing: 2858835419.jpg
[194/200] Processing: 2618322793.jpg
[195/200] Processing: 7425257042.jpg
[196/200] Processing: 8220955383.jpg
[197/200] Processing: 4560100704.jpg
[198/200] Processing: 4718118294.jpg
[199/200] Processing: 2173677067.jpg
[200/200] Processing: 4571650064.jpg
Saved to /kaggle/working/rag_quality_vs_recall_200.csv at 200 samples

,image_name,image_path,retrieved_captions,retrieved_scores,retrieved_image_names,hit@1,hit@5,hit@10,raw_rag,answer_rag
0,3202798691.jpg,/kaggle/input/datasets/hsankesara/flickr-image...,"[ One man in the distance on a bicycle ., A p...","[0.357150673866272, 0.3559662699699402, 0.3517...","[7357208586.jpg, 3090398639.jpg, 3202798691.jp...",0,1,1,A man in a white shirt rides a bicycle with a ...,A man in a white shirt rides a bicycle with a ...
1,4888378326.jpg,/kaggle/input/datasets/hsankesara/flickr-image...,[ A group of friends seated on concrete waitin...,"[0.38841867446899414, 0.37977102398872375, 0.3...","[137431115.jpg, 301582255.jpg, 67210694.jpg, 2...",0,0,0,A group of people waiting for something.,A group of people waiting for something.
2,4196910882.jpg,/kaggle/input/datasets/hsankesara/flickr-image...,[ Two men with guitars singing and playing the...,"[0.36189359426498413, 0.35566991567611694, 0.3...","[2351694146.jpg, 5338988058.jpg, 7438195398.jp...",0,0,0,Two men with guitars singing and playing their...,Two men with guitars singing and playing their...
3,2437917174.jpg,/kaggle/input/datasets/hsankesara/flickr-image...,[ An ethnic woman smiling while writing at a d...,"[0.3485769033432007, 0.336421400308609, 0.3353...","[2437917174.jpg, 2437917174.jpg, 3726935024.jp...",1,1,1,An ethnic woman smiling while writing at a desk.,An ethnic woman smiling while writing at a desk.
4,3246788996.jpg,/kaggle/input/datasets/hsankesara/flickr-image...,"[ Pleople at a party , their backs to the came...","[0.3339836299419403, 0.32579919695854187, 0.32...","[3336759846.jpg, 3114944484.jpg, 3475092236.jp...",0,0,0,Three people at with their backs to the camera...,Three people at with their backs to the camera...

### Analyzing response quality

In [25]:
from collections import defaultdict

gt_map = defaultdict(list)
for _, row in df.iterrows():
    gt_map[str(row["image_name"]).strip()].append(str(row["comment"]).strip())

df_rag_recall["references"] = df_rag_recall["image_name"].map(gt_map)
df_eval = df_rag_recall[df_rag_recall["references"].notna()].copy()

In [26]:
import numpy as np
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

smooth = SmoothingFunction().method1
rouge = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

def bleu_against_refs(pred, refs):
    pred_tokens = pred.split()
    ref_tokens = [r.split() for r in refs]
    return sentence_bleu(ref_tokens, pred_tokens, smoothing_function=smooth)

def best_rouge_against_refs(pred, refs):
    best = {"rouge1": 0.0, "rouge2": 0.0, "rougeL": 0.0}
    for ref in refs:
        scores = rouge.score(ref, pred)
        for k in best:
            best[k] = max(best[k], scores[k].fmeasure)
    return best

In [27]:
rag_bleu = []
rag_r1, rag_r2, rag_rL = [], [], []

for _, row in df_eval.iterrows():
    refs = row["references"]
    pred = str(row["answer_rag"]).strip()

    rag_bleu.append(bleu_against_refs(pred, refs))

    rs = best_rouge_against_refs(pred, refs)
    rag_r1.append(rs["rouge1"])
    rag_r2.append(rs["rouge2"])
    rag_rL.append(rs["rougeL"])

df_eval["bleu_rag"] = rag_bleu
df_eval["rouge1_rag"] = rag_r1
df_eval["rouge2_rag"] = rag_r2
df_eval["rougeL_rag"] = rag_rL

In [28]:
@torch.no_grad()
def compute_clipscore_single(img_path, caption):
    img = Image.open(img_path).convert("RGB")
    img_in = preprocess(img).unsqueeze(0).to(device)
    img_feat = clip_model.encode_image(img_in)
    img_feat = img_feat / img_feat.norm(dim=-1, keepdim=True)

    tokens = open_clip.tokenize([caption]).to(device)
    txt_feat = clip_model.encode_text(tokens)
    txt_feat = txt_feat / txt_feat.norm(dim=-1, keepdim=True)

    return (img_feat * txt_feat).sum(dim=-1).item()

In [29]:
clip_scores = []
for _, row in df_eval.iterrows():
    clip_scores.append(
        compute_clipscore_single(row["image_path"], str(row["answer_rag"]).strip())
    )

df_eval["clipscore_rag"] = clip_scores

In [30]:
def summarize_by_hit(df_eval, hit_col):
    rows = []

    for val in [0, 1]:
        sub = df_eval[df_eval[hit_col] == val]

        if len(sub) == 0:
            continue

        rows.append({
            "Group": f"{hit_col}={val}",
            "Count": len(sub),

            "BLEU": f"{sub['bleu_rag'].mean():.4f} ± {sub['bleu_rag'].std():.4f}",
            "ROUGE-1": f"{sub['rouge1_rag'].mean():.4f} ± {sub['rouge1_rag'].std():.4f}",
            "ROUGE-2": f"{sub['rouge2_rag'].mean():.4f} ± {sub['rouge2_rag'].std():.4f}",
            "ROUGE-L": f"{sub['rougeL_rag'].mean():.4f} ± {sub['rougeL_rag'].std():.4f}",
            "CLIPScore": f"{sub['clipscore_rag'].mean():.4f} ± {sub['clipscore_rag'].std():.4f}"
        })

    return pd.DataFrame(rows)

In [31]:
summary_hit1 = summarize_by_hit(df_eval, "hit@1")
summary_hit5 = summarize_by_hit(df_eval, "hit@5")
summary_hit10 = summarize_by_hit(df_eval, "hit@10")

print("=== Quality vs hit@1 ===")
print(summary_hit1)

print("\n=== Quality vs hit@5 ===")
print(summary_hit5)

print("\n=== Quality vs hit@10 ===")
print(summary_hit10)

=== Quality vs hit@1 ===
     Group  Count             BLEU          ROUGE-1          ROUGE-2  \
0  hit@1=0    101  0.2408 ± 0.2618  0.5531 ± 0.2177  0.3389 ± 0.2712
1  hit@1=1     99  0.5957 ± 0.3173  0.8207 ± 0.2103  0.7129 ± 0.3090

           ROUGE-L        CLIPScore
0  0.5217 ± 0.2232  0.3331 ± 0.0309
1  0.8026 ± 0.2258  0.3594 ± 0.0388

=== Quality vs hit@5 ===
     Group  Count             BLEU          ROUGE-1          ROUGE-2  \
0  hit@5=0     65  0.1637 ± 0.1825  0.4922 ± 0.1865  0.2604 ± 0.2084
1  hit@5=1    135  0.5382 ± 0.3316  0.7787 ± 0.2257  0.6510 ± 0.3259

           ROUGE-L        CLIPScore
0  0.4524 ± 0.1827  0.3314 ± 0.0302
1  0.7610 ± 0.2383  0.3532 ± 0.0385

=== Quality vs hit@10 ===
      Group  Count             BLEU          ROUGE-1          ROUGE-2  \
0  hit@10=0     44  0.1460 ± 0.1501  0.4654 ± 0.1717  0.2363 ± 0.1771
1  hit@10=1    156  0.4928 ± 0.3400  0.7477 ± 0.2362  0.6052 ± 0.3378

           ROUGE-L        CLIPScore
0  0.4274 ± 0.1639  0.3279 ± 0.0322
1  0.7265 ± 0.2502  0.3513 ± 0.0372

In [32]:
overall_rows = []

for hit_col in ["hit@1", "hit@5", "hit@10"]:
    for val in [0, 1]:
        sub = df_eval[df_eval[hit_col] == val]
        if len(sub) == 0:
            continue

        overall_rows.append({
            "Condition": f"{hit_col}={val}",
            "Count": len(sub),

            "BLEU": f"{sub['bleu_rag'].mean():.4f} ± {sub['bleu_rag'].std():.4f}",
            "ROUGE-1": f"{sub['rouge1_rag'].mean():.4f} ± {sub['rouge1_rag'].std():.4f}",
            "ROUGE-2": f"{sub['rouge2_rag'].mean():.4f} ± {sub['rouge2_rag'].std():.4f}",
            "ROUGE-L": f"{sub['rougeL_rag'].mean():.4f} ± {sub['rougeL_rag'].std():.4f}",
            "CLIPScore": f"{sub['clipscore_rag'].mean():.4f} ± {sub['clipscore_rag'].std():.4f}"
        })

quality_vs_recall_df = pd.DataFrame(overall_rows)
quality_vs_recall_df

,Condition,Count,BLEU,ROUGE-1,ROUGE-2,ROUGE-L,CLIPScore
0,hit@1=0,101,0.2408 ± 0.2618,0.5531 ± 0.2177,0.3389 ± 0.2712,0.5217 ± 0.2232,0.3331 ± 0.0309
1,hit@1=1,99,0.5957 ± 0.3173,0.8207 ± 0.2103,0.7129 ± 0.3090,0.8026 ± 0.2258,0.3594 ± 0.0388
2,hit@5=0,65,0.1637 ± 0.1825,0.4922 ± 0.1865,0.2604 ± 0.2084,0.4524 ± 0.1827,0.3314 ± 0.0302
3,hit@5=1,135,0.5382 ± 0.3316,0.7787 ± 0.2257,0.6510 ± 0.3259,0.7610 ± 0.2383,0.3532 ± 0.0385
4,hit@10=0,44,0.1460 ± 0.1501,0.4654 ± 0.1717,0.2363 ± 0.1771,0.4274 ± 0.1639,0.3279 ± 0.0322
5,hit@10=1,156,0.4928 ± 0.3400,0.7477 ± 0.2362,0.6052 ± 0.3378,0.7265 ± 0.2502,0.3513 ± 0.0372

In [33]:
def compute_improvement(df_eval, hit_col):
    sub0 = df_eval[df_eval[hit_col] == 0]
    sub1 = df_eval[df_eval[hit_col] == 1]

    if len(sub0) == 0 or len(sub1) == 0:
        return None

    print(f"\n=== Improvement for {hit_col} ===")
    print(f"Count (0): {len(sub0)}, Count (1): {len(sub1)}")

    for metric in ["bleu_rag", "rouge1_rag", "rouge2_rag", "rougeL_rag", "clipscore_rag"]:
        gain = sub1[metric].mean() - sub0[metric].mean()
        print(f"{metric}: +{gain:.4f}")

In [34]:
for hit_col in ["hit@1", "hit@5", "hit@10"]:
    compute_improvement(df_eval, hit_col)

=== Improvement for hit@1 ===
Count (0): 101, Count (1): 99
bleu_rag: +0.3548
rouge1_rag: +0.2676
rouge2_rag: +0.3741
rougeL_rag: +0.2809
clipscore_rag: +0.0263

=== Improvement for hit@5 ===
Count (0): 65, Count (1): 135
bleu_rag: +0.3745
rouge1_rag: +0.2865
rouge2_rag: +0.3906
rougeL_rag: +0.3086
clipscore_rag: +0.0219

=== Improvement for hit@10 ===
Count (0): 44, Count (1): 156
bleu_rag: +0.3468
rouge1_rag: +0.2823
rouge2_rag: +0.3689
rougeL_rag: +0.2991
clipscore_rag: +0.0234

### Conducting significance test to see whether the result is significant

In [35]:
!pip install scipy

Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from scipy) (2.0.2)

In [36]:
from scipy.stats import ttest_ind

def significance_test(df_eval, hit_col):
    sub0 = df_eval[df_eval[hit_col] == 0]
    sub1 = df_eval[df_eval[hit_col] == 1]

    if len(sub0) == 0 or len(sub1) == 0:
        return None

    print(f"\n=== Significance test for {hit_col} ===")

    for metric in ["bleu_rag", "rouge1_rag", "rouge2_rag", "rougeL_rag", "clipscore_rag"]:
        stat, pval = ttest_ind(sub1[metric], sub0[metric], equal_var=False)

        print(f"{metric}: p-value = {pval:.6f}")

In [37]:
for hit_col in ["hit@1", "hit@5", "hit@10"]:
    significance_test(df_eval, hit_col)

=== Significance test for hit@1 ===
bleu_rag: p-value = 0.000000
rouge1_rag: p-value = 0.000000
rouge2_rag: p-value = 0.000000
rougeL_rag: p-value = 0.000000
clipscore_rag: p-value = 0.000000

=== Significance test for hit@5 ===
bleu_rag: p-value = 0.000000
rouge1_rag: p-value = 0.000000
rouge2_rag: p-value = 0.000000
rougeL_rag: p-value = 0.000000
clipscore_rag: p-value = 0.000022

=== Significance test for hit@10 ===
bleu_rag: p-value = 0.000000
rouge1_rag: p-value = 0.000000
rouge2_rag: p-value = 0.000000
rougeL_rag: p-value = 0.000000
clipscore_rag: p-value = 0.000098